### ISSUE TITLE
java buildpack giving error while creating offline package with OFFLINE=true

### ISSUE THREAD

**Issue by ashijay** [cloudfoundry/java-buildpack#1080]
Hi there!

I am trying to create cloudfoundry offline java package which is giving error as below.

Per instructions provided at https://github.com/cloudfoundry/java-buildpack#offline-package:
bundle install --- worked fine
bundle exec rake clean package --- worked fine
bundle exec rake clean package PINNED=true --- also worked fine
bundle exec rake clean package OFFLINE=true PINNED=true --- gives error

I am building this on ubuntu machine (details below):
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Error snapshot:
# bundle exec rake clean package OFFLINE=true PINNED=true
[DownloadCache]                  WARN  Unable to download https://java-buildpack.cloudfoundry.org/groovy/index.yml into cache build/staging/resources/cache: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
rake aborted!
Unable to find cached file for https://java-buildpack.cloudfoundry.org/groovy/index.yml
/home/ashishj/test_folder_sh/java-buildpack/lib/java_buildpack/util/cache/download_cache.rb:79:in `get'
/home/ashishj/test_folder_sh/java-buildpack/rakelib/dependency_cache_task.rb:147:in `get_from_cache'
/home/ashishj/test_folder_sh/java-buildpack/rakelib/dependency_cache_task.rb:139:in `block (2 levels) in uris'
/home/ashishj/test_folder_sh/java-buildpack/rakelib/dependency_cache_task.rb:137:in `each'
/home/ashishj/test_folder_sh/java-buildpack/rakelib/dependency_cache_task.rb:137:in `block in uris'
/home/ashishj/test_folder_sh/java-buildpack/rakelib/dependency_cache_task.rb:136:in `each'
/home/ashishj/test_folder_sh/java-buildpack/rakelib/dependency_cache_task.rb:136:in `uris'
/home/ashishj/test_folder_sh/java-buildpack/rakelib/dependency_cache_task.rb:48:in `initialize'
/home/ashishj/test_folder_sh/java-buildpack/Rakefile:42:in `new'
/home/ashishj/test_folder_sh/java-buildpack/Rakefile:42:in `<top (required)>'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Tried to start on a solution with https://stackoverflow.com/questions/44227963/cloudfoundry-buildpack-compilation-fails-due-to-certificate-issue but the file container_certificate_trust_store.rb itself is not present in the path lib\java_buildpack\framework

Additionally bundle exec rake versions gives the same error.

Thank you for any input on this.

**Comment by ashijay** [comment]
Realized one more mis-match while pinning the version for offline buildpack.
bionic/jammy has jvmkill-1.17.0-RELEASE version released but not in trusty.

**Comment by ArvindChaturvedi** [comment]
@ashijay : Were you able to resolve this? I am also facing the same and seems like it is happening for Trusty machines as I was able to build an offline build-pack for this release in my local. 

$ bundle exec rake versions
[VersionResolver]                WARN  Discarding illegal version 1.28.0-RC2: Invalid micro version '0-RC2'
[VersionResolver]                WARN  Discarding illegal version 1.28.0-RC3: Invalid micro version '0-RC3'
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                      Java Buildpack 9064578d                                                                                                                      |
+----------------------------------+----------------+------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+
| AppDynamics Agent                | 24.5.0_36037   |                                                                                    | [Release Notes](https://docs.appdynamics.com/appd/onprem/24.x/latest/en/product-and-release-announcements/release-notes) |
| Azure Application Insights Agent | 3.5.3          |                                                                                    | [Release Notes](https://github.com/Microsoft/ApplicationInsights-Java/releases)                                          |
| CA Introscope APM Framework      | 24.4.2_8       |                                                                                    |                                                                                                                          |
| Client Certificate Mapper        | 2.0.1          | Included inline above                                                              | Included inline above                                                                                                    |
| Container Security Provider      | 1.20.0_RELEASE | Included inline above                                                              | Included inline above                                                                                                    |
| Contrast Security Agent          | 6.5.3          |                                                                                    | [Release Notes](https://docs.contrastsecurity.com/en/java-agent-release-notes-and-archive.html)                          |
| Datadog APM Javaagent            | 1.35.2         |                                                                                    | [Release Notes](https://github.com/DataDog/dd-trace-java/releases)                                                       |
| Elastic APM Agent                | 1.50.0         |                                                                                    | [Release Notes](https://www.elastic.co/guide/en/apm/agent/java/current/release-notes.html)                               |
| Gemalto Luna Security Provider   | 7.4.0          |                                                                                    | [Release Notes](https://www.thalesdocs.com/gphsm/luna/7/docs/network/Content/CRN/Luna/CRN_Luna.htm)                      |
| Geode Tomcat Session Store       | 1.14.9         |                                                                                    |                                                                                                                          |
| Google Stackdriver Profiler      | 0.1.0          |                                                                                    | [Release Notes](https://cloud.google.com/profiler/docs/release-notes)                                                    |
| Groovy                           | 2.5.23         |                                                                                    | [Release Notes](http://www.groovy-lang.org/releases.html)                                                                |
| JaCoCo Agent                     | 0.8.12         |                                                                                    | [Release Notes](https://github.com/jacoco/jacoco/releases)                                                               |
| Java CFEnv                       | 3.1.5          |                                                                                    | [Release Notes](https://github.com/pivotal-cf/java-cfenv/releases)                                                       |
| Java Memory Assistant Agent      | 0.5.0          |                                                                                    |                                                                                                                          |
| Java Memory Assistant Clean Up   | 0.1.0          |                                                                                    |                                                                                                                          |
| JProfiler Profiler               | 13.0.7         |                                                                                    | [ChangeLog](https://www.ej-technologies.com/download/jprofiler/changelog.html)                                           |
| JRebel Agent                     | 2024.2.2       |                                                                                    | [ChangeLog](https://www.jrebel.com/products/jrebel/changelog)                                                            |
| jvmkill Agent                    | 1.17.0_RELEASE | Included inline above                                                              | Included inline above                                                                                                    |
| MariaDB JDBC Driver              | 2.7.9          |                                                                                    | [Release Notes](https://mariadb.com/kb/en/mariadb-connector-j-2-7-9-release-notes/)                                      |
| Memory Calculator                | 3.13.0_RELEASE | Included inline above                                                              | Included inline above                                                                                                    |
| Metric Writer                    | 3.5.0_RELEASE  | Included inline above                                                              | Included inline above                                                                                                    |
| New Relic Agent                  | 8.12.0         |                                                                                    | [Release Notes](https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/)                    |
| Open Telemetry Agent             | 2.5.0          |                                                                                    | [Release Notes](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases)                           |
| OpenJDK JRE 11                   | 11.0.23_10     | [Risk Matrix](https://www.oracle.com/security-alerts/cpuapr2024.html#AppendixJAVA) | [Release Notes](https://docs.bell-sw.com/liberica-jdk/11.0.23b10/general/release-notes/)                                 |
| OpenJDK JRE 17                   | 17.0.11_10     | [Risk Matrix](https://www.oracle.com/security-alerts/cpuapr2024.html#AppendixJAVA) | [Release Notes](https://docs.bell-sw.com/liberica-jdk/17.0.11b10/general/release-notes/)                                 |
| OpenJDK JRE 21                   | 21.0.3_10      | [Risk Matrix](https://www.oracle.com/security-alerts/cpujan2024.html#AppendixJAVA) | [Release Notes](https://docs.bell-sw.com/liberica-jdk/21.0.3b10/general/release-notes/)                                  |
| OpenJDK JRE 8                    | 1.8.0_412      | [Risk Matrix](https://www.oracle.com/security-alerts/cpuapr2024.html#AppendixJAVA) | [Release Notes](https://docs.bell-sw.com/liberica-jdk/8u412b9/general/release-notes/)                                    |
| PostgreSQL JDBC Driver           | 42.7.3         |                                                                                    | [ChangeLog](https://jdbc.postgresql.org/documentation/changelog.html)                                                    |
| Redis Session Store              | 1.3.6_RELEASE  | Included inline above                                                              | Included inline above                                                                                                    |
| Riverbed Appinternals Agent      | 11.8.5_BL527   |                                                                                    |                                                                                                                          |
| SeaLights Agent                  | 4.0.2528       |                                                                                    |                                                                                                                          |
| SkyWalking                       | 9.2.0          |                                                                                    | [ChangeLog](https://github.com/apache/skywalking/tree/master/changes)                                                    |
| Splunk OpenTelemetry Java Agent  | 1.32.2         |                                                                                    | [Release Notes](https://github.com/signalfx/splunk-otel-java/releases)                                                   |
| Spring Auto-reconfiguration      | 2.12.0_RELEASE | Included inline above                                                              | Included inline above                                                                                                    |
| Spring Boot CLI                  | 2.7.18         |                                                                                    |                                                                                                                          |
| Spring Boot Container Customizer | 2.6.0_RELEASE  | Included inline above                                                              | Included inline above                                                                                                    |
| Takipi Agent                     | 4.73.3         |                                                                                    | [Release Notes](https://doc.overops.com/docs/whats-new)                                                                  |
| Tomcat 10.1                      | 10.1.25        | [Security](https://tomcat.apache.org/security-10.html)                             | [ChangeLog](https://tomcat.apache.org/tomcat-10.1-doc/changelog.html)                                                    |
| Tomcat 9                         | 9.0.90         | [Security](https://tomcat.apache.org/security-9.html)                              | [ChangeLog](https://tomcat.apache.org/tomcat-9.0-doc/changelog.html)                                                     |
| Tomcat Access Logging Support    | 3.4.0_RELEASE  | Included inline above                                                              | Included inline above                                                                                                    |
| Tomcat Lifecycle Support         | 3.4.0_RELEASE  | Included inline above                                                              | Included inline above                                                                                                    |
| Tomcat Logging Support           | 3.4.0_RELEASE  | Included inline above                                                              | Included inline above                                                                                                    |
| YourKit Profiler                 | 2024.3.157     |                                                                                    | [Release Notes](https://www.yourkit.com/download/yjp_2024_3_builds.jsp)                                                  |
+----------------------------------+----------------+------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+

**Comment by ashijay** [comment]
Hi @ArvindChaturvedi,
Heard no solutions yet. I was also able to build offline too taking the latest code source but its not compatible.

It throws error which malformed the URL and remove trusty from it.

Error:
[Buildpack]                      ERROR Finalize failed with exception #<RuntimeError: Jvmkill Agent error: Unable to find cached file for https://java-buildpack.cloudfoundry.org/jvmkill//x86_64/index.yml>

**Comment by pivotal-david-osullivan** [comment]
Hi, the buildpack supports Bionic and Jammy and publishes binaries for these where relevant.

There were binaries available for Trusty when it was under general support, however you would need to fork the buildpack, specify Trusty as a packaging platform, and return to older versions of binaries to package, which would not be recommended. 

Have you investigated migrating to Jammy?

**Comment by A661182** [comment]
Anyone fine any solution or workaround to this ?
I am facing similar issue for trusty:
   [DownloadCache]                  WARN  Unable to download https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml into cache /tmp/cache/final: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
   [Buildpack]                      ERROR Finalize failed with exception #<RuntimeError: Jvmkill Agent error: Unable to find cached file for https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml>
   Jvmkill Agent error: Unable to find cached file for https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml
   Failed to compile droplet: Failed to run finalize script: exit status 1

**Comment by riddhichheda03** [comment]
Anyone found any solution or workaround to this ?
I am facing similar issue :
[DownloadCache] WARN Unable to download https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml into cache /tmp/cache/final: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
[Buildpack] ERROR Finalize failed with exception #<RuntimeError: Jvmkill Agent error: Unable to find cached file for https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml>
Jvmkill Agent error: Unable to find cached file for https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/index.yml
Failed to compile droplet: Failed to run finalize script: exit status 1
