### ISSUE TITLE
[java main] gradle build error - A problem occurred evaluating project ':dist-zip-application'.

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/java-buildpack#128]
```
$ cd java-main-application
$ gradle build --stacktrace

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/drnic/Projects/cloudfoundry/java-test-applications/dist-zip-application/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':dist-zip-application'.
> org/gradle/api/tasks/compile/Compile

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':dist-zip-application'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:148)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
```

I'm on OS X and installed gradle from home brew. How do I build the gradle apps?

**Comment by drnic** [comment]
I get the same issue with the `dist-zip-application` project.

**Comment by drnic** [comment]
Sorry, I didn't realise I needed to use the build tools in root folder.
