### ISSUE TITLE
ERR undefined method `[]' for nil:NilClass during Spring Application deployment

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry/java-buildpack#129]
Hi,
I have an application running, which could be deployed till yesterday without any issues. Today I am getting the following exception:

````trace
2015-01-15T21:17:04.67+0100 [API]     OUT Updated app with guid 4e9332a4-74a1-4333-af43-4863d6bb2697 ({"state"=>"STOPPED"})
2015-01-15T21:17:05.67+0100 [DEA]     OUT Got staging request for app with id 4e9332a4-74a1-4333-af43-4863d6bb2697
2015-01-15T21:17:07.23+0100 [API]     OUT Updated app with guid 4e9332a4-74a1-4333-af43-4863d6bb2697 ({"state"=>"STARTED"})
2015-01-15T21:17:07.93+0100 [STG]     OUT -----> Downloaded app package (48M)
2015-01-15T21:17:08.18+0100 [STG]     ERR Cloning into '/tmp/buildpacks/java-buildpack'...
2015-01-15T21:17:12.16+0100 [STG]     OUT -----> Java Buildpack Version: 6f3de1a | https://github.com/cloudfoundry/java-buildpack.git#6f3de1a
2015-01-15T21:17:15.96+0100 [STG]     OUT -----> Downloading Open Jdk JRE 1.8.0_25 from https://download.run.pivotal.io/openjdk/lucid/x86_64/openjdk-1.8.0_25.tar.gz (3.6s)
2015-01-15T21:17:17.37+0100 [STG]     OUT        Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.4s)
2015-01-15T21:17:17.60+0100 [STG]     OUT -----> Downloading Spring Auto Reconfiguration 1.5.0_RELEASE from https://download.run.pivotal.io/auto-reconfiguration/auto-reconfiguration-1.5.0_RELEASE.jar (0.2s)
2015-01-15T21:17:18.57+0100 [STG]     OUT -----> Downloading Tomcat Instance 8.0.15 from https://download.run.pivotal.io/tomcat/tomcat-8.0.15.tar.gz (0.9s)
2015-01-15T21:17:18.75+0100 [STG]     OUT        Expanding Tomcat to .java-buildpack/tomcat (0.1s)
2015-01-15T21:17:18.83+0100 [STG]     OUT -----> Downloading Tomcat Lifecycle Support 2.4.0_RELEASE from https://download.run.pivotal.io/tomcat-lifecycle-support/tomcat-lifecycle-support-2.4.0_RELEASE.jar (0.0s)
2015-01-15T21:17:18.92+0100 [STG]     OUT -----> Downloading Tomcat Logging Support 2.4.0_RELEASE from https://download.run.pivotal.io/tomcat-logging-support/tomcat-logging-support-2.4.0_RELEASE.jar (0.0s)
2015-01-15T21:17:18.94+0100 [STG]     OUT -----> Downloading Tomcat Access Logging Support 2.4.0_RELEASE from https://download.run.pivotal.io/tomcat-access-logging-support/tomcat-access-logging-support-2.4.0_RELEASE.jar (0.0s)
2015-01-15T21:17:19.77+0100 [STG]     ERR [Buildpack]                      ERROR Release failed with exception #<NoMethodError: undefined method `[]' for nil:NilClass>
2015-01-15T21:17:19.78+0100 [STG]     ERR undefined method `[]' for nil:NilClass
2015-01-15T21:17:19.79+0100 [STG]     OUT Staging failed: Release info failed:
2015-01-15T21:17:20.04+0100 [API]     ERR Encountered error: App staging failed in the buildpack release phase
````

My deployment manifest.yml looks like that:

````yml
instances: 1
timeout: 180
memory: 1024M
applications:
## Web
- name: web
  host: dev-api
  domain: bla.com
  path: target/web.war
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
  services:
  - mongodb
  - postgresql
  - rabbitmq
````

Any idea what's wrong? :-( Tried rebooting runner/api/api_worker and changing the organisation/space, without any different result.

**Comment by jhiemer** [comment]
This seems to be an issue with gemfire in tomcat:

````java
2015-01-16T10:51:20.06+0100 [STG]     ERR [MemoryBucket]                   DEBUG #<JavaBuildpack::Jre::MemoryBucket:0x00000001dfba28 @name="heap", @weighting=75, @range=0..>
2015-01-16T10:51:20.06+0100 [STG]     ERR [MemoryBucket]                   DEBUG #<JavaBuildpack::Jre::MemoryBucket:0x00000001dfa470 @name="metaspace", @weighting=10, @range=64M..>
2015-01-16T10:51:20.06+0100 [STG]     ERR [MemoryBucket]                   DEBUG #<JavaBuildpack::Jre::StackMemoryBucket:0x00000001df8e68 @name="stack", @weighting=5, @range=0..>
2015-01-16T10:51:20.06+0100 [STG]     ERR [MemoryBucket]                   DEBUG #<JavaBuildpack::Jre::MemoryBucket:0x00000001f60be8 @name="native", @weighting=10, @range=0..>
2015-01-16T10:51:20.06+0100 [STG]     ERR [MemoryBucket]                   DEBUG #<JavaBuildpack::Jre::MemoryBucket:0x00000001f5ed98 @name="normalised stack", @weighting=5, @range=0..>
2015-01-16T10:51:20.06+0100 [STG]     ERR [Buildpack]                      ERROR Release failed with exception #<NoMethodError: undefined method `[]' for nil:NilClass>
2015-01-16T10:51:20.06+0100 [STG]     ERR [Buildpack]                      DEBUG Exception #<NoMethodError: undefined method `[]' for nil:NilClass> backtrace:
2015-01-16T10:51:20.06+0100 [STG]     ERR /tmp/buildpacks/java-buildpack/lib/java_buildpack/container/tomcat/tomcat_gemfire_store.rb:61:in `command'
2015-01-16T10:51:20.06+0100 [STG]     ERR /tmp/buildpacks/java-buildpack/lib/java_buildpack/component/modular_component.rb:55:in `release'
2015-01-16T10:51:20.06+0100 [STG]     ERR /tmp/buildpacks/java-buildpack/lib/java_buildpack/component/modular_component.rb:54:in `map'
2015-01-16T10:51:20.06+0100 [STG]     ERR /tmp/buildpacks/java-buildpack/lib/java_buildpack/component/modular_component.rb:54:in `release'
2015-01-16T10:51:20.06+0100 [STG]     ERR /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:77:in `release'
2015-01-16T10:51:20.06+0100 [STG]     ERR /tmp/buildpacks/java-buildpack/bin/release:27:in `block in <main>'
2015-01-16T10:51:20.06+0100 [STG]     ERR /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:203:in `with_buildpack'
2015-01-16T10:51:20.06+0100 [STG]     ERR /tmp/buildpacks/java-buildpack/bin/release:26:in `<main>'
````

@nebhale is this a bug in the buildpack? `Java Buildpack Version: 6f3de1a`

**Comment by gaurav1416** [comment]
We also faced same error while deploying simple spring app.
I am adding log snippet here
 2015-01-16T09:58:07.000+00:00 [STG] ERR undefined method `[]' for nil:NilClass
2015-01-16T09:58:06.000+00:00 [STG] OUT -----> Downloading Tomcat Instance 8.0.15 from https://download.run.pivotal.io/tomcat/tomcat-8.0.15.tar.gz (0.4s)
2015-01-16T09:58:02.000+00:00 [STG] OUT -----> Downloaded app package (532K)
2015-01-16T09:57:45.000+00:00 [API] OUT Updated app with guid fa07f4f1-96c4-47c6-b377-a50549a6d1e2 ({"route"=>"9223f924-74c0-4964-bd0e-277f87773121"})
2015-01-16T09:58:07.000+00:00 [API] ERR Encountered error: App staging failed in the buildpack release phase
2015-01-16T09:58:01.000+00:00 [API] OUT Updated app with guid fa07f4f1-96c4-47c6-b377-a50549a6d1e2 ({"state"=>"STARTED"})
2015-01-16T09:58:07.000+00:00 [STG] ERR [Buildpack] ERROR Release failed with exception #<NoMethodError: undefined method `[]' for nil:NilClass>
2015-01-16T09:58:06.000+00:00 [STG] ERR

**Comment by ramonskie** [comment]
seems to be related to this commit 
https://github.com/cloudfoundry/java-buildpack/commit/f50f32885df27a662ee80dbc4840c027c4feccd0

**Comment by jhiemer** [comment]
This seems to related to a recent commit here:

https://github.com/cloudfoundry/java-buildpack/blob/master/lib/java_buildpack/container/tomcat/tomcat_gemfire_store.rb#L60

two days ago.

**Comment by ramonskie** [comment]
add @nebhale & @cgfrost as participant

**Comment by cgfrost** [comment]
I'm looking at this now, I will back the commit out unless the solution can be found quickly.

**Comment by ramonskie** [comment]
damn that was quick :+1:

**Comment by jhiemer** [comment]
perfect thanks!
