### ISSUE TITLE
GemFire 8.1 requires log4j

### ISSUE THREAD

**Issue by monkeyherder** [cloudfoundry/java-buildpack#144]
In 9858440401dae5c637d544ebcb3c2e0ade8a3132 GemFire version was upgraded to 8.1. While deploying an app using GemFire session replication we encountered the following Error:
```
2015-02-18T10:38:59.09-0800 [App/0]   OUT Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
2015-02-18T10:38:59.09-0800 [App/0]   OUT 	at java.lang.ClassLoader.defineClass1(Native Method)
2015-02-18T10:38:59.09-0800 [App/0]   OUT 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
2015-02-18T10:38:59.09-0800 [App/0]   OUT 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2015-02-18T10:38:59.09-0800 [App/0]   OUT 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
2015-02-18T10:38:59.09-0800 [App/0]   OUT 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2015-02-18T10:38:59.09-0800 [App/0]   OUT 	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
2015-02-18T10:38:59.09-0800 [App/0]   OUT 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
2015-02-18T10:38:59.09-0800 [App/0]   OUT 	at java.security.AccessController.doPrivileged(Native Method)
...
```

It looks like log4j (which is a new dependency in 8.1) is not properly included on the class path.

**Comment by cgfrost** [comment]
Hi,

I've created this issue to cover the work. https://www.pivotaltracker.com/story/show/88683258

I have no way of knowing when new versions of GemFire has a new dependency and we are not willing to test every dependency we maintain when a new version comes out as there are simply too many.

Chris.

**Comment by cgfrost** [comment]
Log4j is now available for use as a dependency in the Java buildpack. Due to other issues we have also moved down to Gem Fire 8.0.* so this hasn't actually been added. We are now aware of this fact and will add it in the future when we are ready to move up to 8.1.*. For now I consider this issue resolved and you should be able to proceed with Gem Fire 8.0.* back in place.
