### ISSUE TITLE
Introscope empty repo breaks offline buildpack creation

### ISSUE THREAD

**Issue by sparameswaran** [cloudfoundry/java-buildpack#180]
Introscope agent repo url is empty and this breaks offline buildpack creation:

```bash
bundle exec rake package OFFLINE=true
[DownloadCache]                  WARN  Unable to download /index.yml into cache build/staging/resources/cache: Connection refused - connect(2)
rake aborted!
Unable to find cached file for /index.yml
java-buildpack/lib/java_buildpack/util/cache/download_cache.rb:67:in `get'
java-buildpack/rakelib/dependency_cache_task.rb:162:in `get_from_cache'
java-buildpack/rakelib/dependency_cache_task.rb:154:in `block (2 levels) in uris'
java-buildpack/rakelib/dependency_cache_task.rb:151:in `each'
java-buildpack/rakelib/dependency_cache_task.rb:151:in `block in uris'
java-buildpack/rakelib/dependency_cache_task.rb:150:in `each'
java-buildpack/rakelib/dependency_cache_task.rb:150:in `uris'
java-buildpack/rakelib/dependency_cache_task.rb:43:in `initialize'
java-buildpack/Rakefile:40:in `new'
java-buildpack/Rakefile:40:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by nebhale** [comment]
Yeah, not surprised to see that.  This would be the first component that's both enabled and cannot work without modification.  We're definitely going to have to discuss how to proceed with this.  I'm include to disable it by default, but I suspect the CA guys aren't going to be happy about that.
