### ISSUE TITLE
No container can run the application

### ISSUE THREAD

**Issue by mrbrdo** [cloudfoundry/java-buildpack#19]
I'm trying to use this with https://github.com/Altoros/cf-vagrant-installer/ to deploy a jruby app, but I get this error:

```
"Staging error: failed to stage application:\nScript exited with status 1\n-----> Downloaded app package (32M)\nInitialized empty Git repository in /tmp/buildpacks/java-buildpack/.git/\nInstalling java-buildpack.\nE, [2013-11-02T01:56:50.480858 #64] ERROR -- /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:49:in `rescue in drive_buildpack_with_logger': Compile failed with exception #<RuntimeError: No container can run the application>\nNo container can run the application\n/vagrant/dea_ng/buildpacks/lib/installer.rb:17:in `compile': Buildpack compilation step failed: (RuntimeError)\n\tfrom /vagrant/dea_ng/buildpacks/lib/buildpack.rb:26:in `block in compile_with_timeout'\n\tfrom /usr/lib/ruby/1.9.1/timeout.rb:68:in `timeout'\n\tfrom /vagrant/dea_ng/buildpacks/lib/buildpack.rb:25:in `compile_with_timeout'\n\tfrom /vagrant/dea_ng/buildpacks/lib/buildpack.rb:16:in `block in stage_application'\n\tfrom /vagrant/dea_ng/buildpacks/lib/buildpack.rb:12:in `chdir'\n\tfrom /vagrant/dea_ng/buildpacks/lib/buildpack.rb:12:in `stage_application'\n\tfrom /vagrant/dea_ng/buildpacks/bin/run:10:in `<main>'\n"
```

I don't have any other apps, I tried deleting this app and restarting the whole server, but I always get this error.

I tried deploying the app normally, or as a war (with --path option to cf push), but neither worked.

**Comment by vineetbadola** [comment]
What is main reason fro below error while staging an application in cloudfoundry
error: java.net.MalformedURLException: no !/ in spec 
Is there something that need to be changed in manifest file
Please help me in this
