### ISSUE TITLE
Support for Cloud Foundry Environment Variable substitution in the JAVA_OPTS framework

### ISSUE THREAD

**Issue by kelapure** [cloudfoundry/java-buildpack#209]
See comments made here https://github.com/cloudfoundry/java-buildpack/issues/205
Use case is very simple. I  need the ability to configure a javaagent with the [$PORT](http://docs.run.pivotal.io/devguide/deploy-apps/environment-variable.html#PORT) CF env. variable.

 I needeto do something like this
`JAVA_OPTS:-javaagent:agent.jar=port=$PORT,host=localhost`

The port that is provided to configure the Jolokia agent is the port the server listens on. This is passed into the droplet as an env. variable by CF. I had trouble getting the droplet to start with the above command. The value of $PORT is not substituted in the JAVA_OPTS env variable. Is there any way to force this to happen. See example below ...

```yaml
2015-07-27T15:10:17.44-0400 [STG/0]      ERR [Buildpack]                      DEBUG Release Payload:
2015-07-27T15:10:17.44-0400 [STG/0]      ERR ---
2015-07-27T15:10:17.44-0400 [STG/0]      ERR addons: []
2015-07-27T15:10:17.44-0400 [STG/0]      ERR config_vars: {}
2015-07-27T15:10:17.44-0400 [STG/0]      ERR default_process_types:
2015-07-27T15:10:17.44-0400 [STG/0]      ERR   web: CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-1.1.1_RELEASE
2015-07-27T15:10:17.44-0400 [STG/0]      ERR     -memorySizes=metaspace:64m.. -memoryWeights=heap:75,metaspace:10,stack:5,native:10
2015-07-27T15:10:17.44-0400 [STG/0]      ERR     -totMemory=$MEMORY_LIMIT) && JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS="-Djava.io.tmpdir=$TMPDIR
2015-07-27T15:10:17.44-0400 [STG/0]      ERR     -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY
2015-07-27T15:10:17.44-0400 [STG/0]      ERR     -javaagent:/home/vcap/app/WEB-INF/lib/jolokia-jvm-1.3.1-agent.jar=port=,host=localhost
2015-07-27T15:10:17.44-0400 [STG/0]      ERR     -Daccess.logging.enabled=false -Dhttp.port=$PORT" $PWD/.java-buildpack/tomcat/bin/catalina.sh
2015-07-27T15:10:17.44-0400 [STG/0]      ERR     run
2015-07-27T15:10:24.93-0400 [STG/17]     OUT -----> Uploading droplet (74M)
2015-07-27T15:10:35.82-0400 [DEA/17]     OUT Starting app instance (index 0) with guid 4284bf4f-95c7-40d0-9290-162837c1bcf8
2015-07-27T15:10:38.76-0400 [App/0]      ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
2015-07-27T15:10:38.76-0400 [App/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-07-27T15:10:38.76-0400 [App/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-07-27T15:10:38.76-0400 [App/0]      ERR    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-07-27T15:10:38.76-0400 [App/0]      ERR    at java.lang.reflect.Method.invoke(Method.java:497)
2015-07-27T15:10:38.76-0400 [App/0]      ERR    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:388)
2015-07-27T15:10:38.76-0400 [App/0]      ERR    at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
2015-07-27T15:10:38.76-0400 [App/0]      ERR Caused by: java.lang.IllegalArgumentException: jolokia: Invalid option 'port='. Ignoring
2015-07-27T15:10:38.76-0400 [App/0]      ERR    at org.jolokia.jvmagent.JvmAgentConfig.split(JvmAgentConfig.java:112)
2015-07-27T15:10:38.76-0400 [App/0]      ERR    at org.jolokia.jvmagent.JvmAgentConfig.<init>(JvmAgentConfig.java:46)
2015-07-27T15:10:38.76-0400 [App/0]      ERR    at org.jolokia.jvmagent.JvmAgent.premain(JvmAgent.java:67)
2015-07-27T15:10:38.76-0400 [App/0]      ERR    ... 6 more
2015-07-27T15:10:38.76-0400 [App/0]      OUT FATAL ERROR in native method: processing of -javaagent failed
2015-07-27T15:10:38.76-0400 [App/0]      ERR bash: line 1:    33 Aborted                 JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS="-Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY -javaagent:/home/vcap/app/WEB-INF/lib/jolokia-jvm-1.3.1-agent.jar=port=,host=localhost -Daccess.logging.enabled=false -Dhttp.port=$PORT" $PWD/.java-buildpack/tomcat/bin/catalina.sh run
```

**Comment by jgawor** [comment]
As a workaround, I think setting the `CATALINA_OPTS` env. variable might work.

**Comment by kelapure** [comment]
@cgfrost still no dice

```shell
$ cf set-env spring-music JAVA_OPTS '-javaagent:/home/vcap/app/WEB-INF/lib/jolokia-jvm-1.3.1-agent.jar=port="'\\\$PORT'",host=localhost'
Setting env variable 'JAVA_OPTS' to '-javaagent:/home/vcap/app/WEB-INF/lib/jolokia-jvm-1.3.1-agent.jar=port="\$PORT",host=localhost' for app spring-music in org pivot-rkelapure / space development as rkelapure@pivotal.io...
OK

bash-3.2$ cf restage spring-music
Restaging app spring-music in org pivot-rkelapure / space development as rkelapure@pivotal.io...

Buildpack]   DEBUG Release Payload:
---
addons: []
config_vars: {}
default_process_types:
  web: JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS="-Djava.io.tmpdir=$TMPDIR
    -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh -Xmx768M
    -Xms768M -XX:MaxMetaspaceSize=104857K -XX:MetaspaceSize=104857K -Xss1M -javaagent:/home/vcap/app/WEB-INF/lib/jolokia-jvm-1.3.1-agent.jar=port=$PORT,host=localhost
    -Daccess.logging.enabled=false -Dhttp.port=$PORT" $PWD/.java-buildpack/tomcat/bin/catalina.sh
    run
-----> Uploading droplet (68M)
```

**Comment by cgfrost** [comment]
@kelapure This looks right to me `jolokia-jvm-1.3.1-agent.jar=port=$PORT,host=localhost` in the web start command, what are you expecting to see?

**Comment by kelapure** [comment]
@cgfrost  The substitution of $PORT with the actual value like 8080.

**Comment by nebhale** [comment]
That happens at execution time, the same way that `$PWD` is evaluated.

**Comment by nebhale** [comment]
Notice that `-Dhttp.port=$PORT` has no value, and yet your application starts and listens properly.

**Comment by kelapure** [comment]
@nebhale ah yes .. this gets substituted at runtime when the container is launched. So the suggestion provided by @cgfrost  is good.

**Comment by nebhale** [comment]
If that's the case, can we close this issue out?

**Comment by kelapure** [comment]
yes you can. Its on me now to figure out why Tomcat is not starting with the right javaagent string. Once I find more I will let you know. The  intent of my experiment is to add Jolokia support to ANY app in CF by setting the correct variable in `JAVA_OPTS` so that JMX mbeans of the tomcat instance in CF can be browsed without any app(war) modifications.  This applies to non-spring boot apps since spring-boot apps have native support for Jolokia.
