### ISSUE TITLE
DB2ServiceInfoCreator not found

### ISSUE THREAD

**Issue by 1123** [cloudfoundry/java-buildpack#215]
I have just built a new offline, pinned buildpack with oracle_jres. When pushing the standard spring-music app with this buildpack, the following error is in the logs:

2015-08-19T17:09:45.85+0200 [App/0]      OUT Caused by: java.util.ServiceConfigurationError: org.springframework.cloud.cloudfoundry.CloudFoundryServiceInfoCreator: Provider or
g.springframework.cloud.cloudfoundry.DB2ServiceInfoCreator not found
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at org.springframework.cloud.AbstractCloudConnector.scanServiceInfoCreators(AbstractCloudConnector.java:53)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at org.springframework.cloud.AbstractCloudConnector.<init>(AbstractCloudConnector.java:33)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at org.springframework.cloud.cloudfoundry.CloudFoundryConnector.<init>(CloudFoundryConnector.java:32)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at java.lang.Class.newInstance(Class.java:442)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
2015-08-19T17:09:45.85+0200 [App/0]      OUT    ... 24 more
2015-08-19T17:09:45.85+0200 [App/0]      OUT [CONTAINER] org.apache.catalina.core.StandardContext           SEVERE  One or more listeners failed to start. Full details will be
 found in the appropriate container log file

When pushing with the standard java buildpack, everything works fine.

**Comment by 1123** [comment]
Seems like this was an issue with spring-auto-configuration 1.9. There was just a new release (1.10), and a buildpack with this release works fine.

**Comment by nebhale** [comment]
Sounds good.  We're having some trouble with a recent upgrade to `spring-cloud-connectors`, so if you see any other odd behavior, please open issues against it.
