### ISSUE TITLE
Overriding memory sizes and heuristics at same time

### ISSUE THREAD

**Issue by johnmcteague** [cloudfoundry/java-buildpack#219]
I'm trying to override both the memory heuristics and size options for my app as follows:
```
  env:
    JBP_CONFIG_ORACLE_JRE: '[jre: {version: 1.7.0_+}, memory_calculator: {memory_heuristics: {heap: 80},  memory_sizes: {stack:256k}}]'
```
Our buildpack is forked to add extra frameworks and components but the core is up to date with commit https://github.com/cloudfoundry/java-buildpack/commit/309e8c5e507ef8eed50dfb8ca79c62f9060a16ea

The following error is produced from the buildpack
```
2015-08-25T16:35:19.49+0100 [STG/0]      ERR [ConfigurationUtils]             DEBUG Configuration from /var/vcap/data/dea_next/admin_buildpacks/d5300a
5b-36b8-43bf-9a26-825fc07bf9ba_c9b0582c0047ea838326b9ac56a6efb6cf880139/config/oracle_jre.yml: {"jre"=>{"version"=>"1.7.0_+", "repository_root"=>"{def
ault.repository.root}/oraclejdk/{platform}/{architecture}"}, "memory_calculator"=>{"version"=>"1.+", "repository_root"=>"{default.repository.root}/mem
ory-calculator/{platform}/{architecture}", "memory_sizes"=>{"metaspace"=>"64m..", "permgen"=>"64m..", "stack"=>nil, "heap"=>nil, "native"=>nil}, "memo
ry_heuristics"=>{"heap"=>75, "metaspace"=>10, "permgen"=>10, "stack"=>5, "native"=>10}}, "jce"=>{"repository_root"=>"{default.repository.root}/jce", "
version"=>"1.8.0"}}
2015-08-25T16:35:19.49+0100 [STG/0]      ERR /usr/lib/ruby/1.9.1/psych.rb:203:in `parse': (<unknown>): found unexpected ':' while scanning a plain sca
lar at line 1 column 94 (Psych::SyntaxError)
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /usr/lib/ruby/1.9.1/psych.rb:203:in `parse_stream'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /usr/lib/ruby/1.9.1/psych.rb:151:in `parse'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /usr/lib/ruby/1.9.1/psych.rb:127:in `load'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /var/vcap/data/dea_next/admin_buildpacks/d5300a5b-36b8-43bf-9a26-825fc07bf9ba_c9b0582c0047ea83832
6b9ac56a6efb6cf880139/lib/java_buildpack/util/configuration_utils.rb:116:in `load_configuration'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /var/vcap/data/dea_next/admin_buildpacks/d5300a5b-36b8-43bf-9a26-825fc07bf9ba_c9b0582c0047ea83832
6b9ac56a6efb6cf880139/lib/java_buildpack/util/configuration_utils.rb:46:in `load'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /var/vcap/data/dea_next/admin_buildpacks/d5300a5b-36b8-43bf-9a26-825fc07bf9ba_c9b0582c0047ea83832
6b9ac56a6efb6cf880139/lib/java_buildpack/buildpack.rb:161:in `block in instantiate'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /var/vcap/data/dea_next/admin_buildpacks/d5300a5b-36b8-43bf-9a26-825fc07bf9ba_c9b0582c0047ea83832
6b9ac56a6efb6cf880139/lib/java_buildpack/buildpack.rb:152:in `map'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /var/vcap/data/dea_next/admin_buildpacks/d5300a5b-36b8-43bf-9a26-825fc07bf9ba_c9b0582c0047ea83832
6b9ac56a6efb6cf880139/lib/java_buildpack/buildpack.rb:152:in `instantiate'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /var/vcap/data/dea_next/admin_buildpacks/d5300a5b-36b8-43bf-9a26-825fc07bf9ba_c9b0582c0047ea83832
6b9ac56a6efb6cf880139/lib/java_buildpack/buildpack.rb:121:in `instantiate_components'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /var/vcap/data/dea_next/admin_buildpacks/d5300a5b-36b8-43bf-9a26-825fc07bf9ba_c9b0582c0047ea83832
6b9ac56a6efb6cf880139/lib/java_buildpack/buildpack.rb:114:in `initialize'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /var/vcap/data/dea_next/admin_buildpacks/d5300a5b-36b8-43bf-9a26-825fc07bf9ba_c9b0582c0047ea83832
6b9ac56a6efb6cf880139/lib/java_buildpack/buildpack.rb:207:in `new'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /var/vcap/data/dea_next/admin_buildpacks/d5300a5b-36b8-43bf-9a26-825fc07bf9ba_c9b0582c0047ea83832
6b9ac56a6efb6cf880139/lib/java_buildpack/buildpack.rb:207:in `with_buildpack'
2015-08-25T16:35:19.49+0100 [STG/0]      ERR    from /var/vcap/data/dea_next/admin_buildpacks/d5300a5b-36b8-43bf-9a26-825fc07bf9ba_c9b0582c0047ea83832
6b9ac56a6efb6cf880139/bin/detect:26:in `<main>'
2015-08-25T16:35:19.56+0100 [STG/0]      OUT     Staging failed: An application could not be etected by any available buildpack
2015-08-25T16:35:19.67+0100 [API/0]      ERR encountered error: An app was not successfully etected by any available buildpack
```

Should I be able to override both at the same time?

**Comment by cgfrost** [comment]
Yes you should, the error means there is a syntax problem in the value of your environment variable. I can't see anything after a quick look at it. It's the end of my working day here, I'll have a proper look tomorrow

**Comment by johnmcteague** [comment]
The character number in question is the colon in the {stack:256k} portion of the variable

**Comment by cgfrost** [comment]
Hi, The value of that you give this environment variable will get parsed as yaml so it needs to be valid yaml. key value pairs must be separated with ": ", notice the space (not including the quotes (silly markdown trims my whitespace in an inline code block)). Add an extra space for the `stack` argument at the end. The yaml parser in Ruby is very picky but this is particularly annoying.

**Comment by johnmcteague** [comment]
Good spot, thanks.
