### ISSUE TITLE
Pushing a wildfly-warm up to cf fails to start the application when using the java-buildpack

### ISSUE THREAD

**Issue by thomasmey** [cloudfoundry/java-buildpack#269]
Hi,

I tried to push my wildfly-swarm app to a cf environment with `cf push ekl -p einkaufsliste-server-server-0.1.0-SNAPSHOT-swarm.jar -b java_buildpack -m 480m`. But the application fails to start because the jar seems to be unpacked on the target.

Exception is:
```
Exception in thread "main" java.lang.ClassNotFoundException: org.wildfly.swarm.Swarm from [Module "swarm.application:main" from BootModuleLoader@27c170f0 for finders [org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder@5451c3a8, org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder@2626b418, org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder@5a07e868, org.wildfly.swarm.bootstrap.modules.ApplicationModuleFinder@76ed5528]]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at org.wildfly.swarm.bootstrap.Main.getMainClass(Main.java:75)
	at org.wildfly.swarm.bootstrap.Main.run(Main.java:50)
	at org.wildfly.swarm.bootstrap.Main.main(Main.java:39)
```

I get the same exception when unpacking the jar locally and trying to run it with `$ java -cp . org.wildly.swarm.bootstrap.Main`

running the jar file locally works correctly:
```
$ java -jar bm/einkaufsliste-server-server-0.1.0-SNAPSHOT-swarm.jar 
tmpDir: /tmp
10:57:28,964 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
10:57:29,788 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0049: WildFly Core 2.0.0.CR8 "Kenny" starting
```

bug or feature or PEBCAK?

**Comment by nebhale** [comment]
Cloud Foundry presents buildpacks with a consistent view of applications during staging.  Since most languages other than Java (i.e. Ruby, Node, etc.) use filesystem layouts instead of archives, Cloud Foundry explodes any archives and presents buildpacks with the exploded version on the filesystem.  The Java buildpack takes this into account, reading the `Main-Class` manifest entry and ensuring that `.` is on the class path when starting applications.  So I'd say this is "works as expected".

**Comment by thomasmey** [comment]
Hi Ben,

I didn't find the time yet to have a closer look at the underlying problem, i.e. why an unpacked wildfly swarm archive won't start.

Anyway I will look into this and I would really like to see wilddly-swarm being supported on cloud foundry environment.

I suspect that maybe ModuleClassLoader can't cope with an unexploded archive.

Anyway thanks for also looking into this problem.

I did search the web for wildfly-swarm, but I did only find reports about running wfs in docker.

With kind regards
Thomas

**Comment by nebhale** [comment]
@thomasmey Looking at [the documentation](http://wildfly-swarm.io), startup should be `java -jar MyApp.jar` which is a "Java Main Application".  Since we already support [reading the `Main-Class` attribute](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-java_main.md) and executing it (that's how `java -jar` works), no changes should need to be made to the buildpack to get Wildfly Swarm to start.  So, as long as you can get Wildfly Swarm to start properly with an exploded archive (a reasonable deployment structure for Java applications) then it will run on Cloud Foundry.

**Comment by thomasmey** [comment]
Yes theoretically it should work unpacked, but for some reason it doesn't. I don't know why. But I'll investigate it in the next days.

**Comment by jswaelens** [comment]
@thomasmey , did you manage to work around this issue? I'm having the same exact one and quite new to cf so any help would be great!
