### ISSUE TITLE
Tomcat fails to start due to unaccessible container_customizer jar

### ISSUE THREAD

**Issue by timeapen** [cloudfoundry/java-buildpack#333]
I have an application that I push up to Cloudfoundry via the following command:

`cf push positions -b  https://github.com/cloudfoundry/java-buildpack.git --hostname aHost-d aDomain -p deployable\positions.war `

The output from the cf push is below.  Note that it is able to download the container_customizer-X.X.X.jar:

```
-----> Downloaded app buildpack cache (45M)
Cloning into '/tmp/buildpacks/java-buildpack'...
-----> Java Buildpack Version: b050954 | https://github.com/cloudfoundry/java-buildpack.git#b050954
-----> Downloading Open Jdk JRE 1.8.0_101 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_101.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.5s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
       Memory Settings: -Xmx681574K -XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K
-----> Downloading Container Customizer 1.0.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-customizer/container-customizer-1.0.0_RELEASE.jar (found in cache)
-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
       Modifying /WEB-INF/web.xml for Auto Reconfiguration
-----> Uploading droplet (84M)
```

The application fails to start however, due to Tomcat not being able to access this jar:

```
2016-09-29T19:14:57.239-0400[App/0]OUTjava.io.IOException: Failed to access resource /WEB-INF/lib/container_customizer-1.0.0_RELEASE.jar
2016-09-29T19:14:57.239-0400[App/0]OUT[2016-09-29 23:14:57.232] boot - 29 ERROR [localhost-startStop-1] --- WebappLoader: LifecycleException
2016-09-29T19:14:57.239-0400[App/0]OUT at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1574)
2016-09-29T19:14:57.239-0400[App/0]OUT at org.apache.catalina.loader.WebappLoader.setRepositories(WebappLoader.java:981)
2016-09-29T19:14:57.239-0400[App/0]OUT at org.apache.catalina.loader.WebappLoader.startInternal(WebappLoader.java:604)
2016-09-29T19:14:57.239-0400[App/0]OUT at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
2016-09-29T19:14:57.239-0400[App/0]OUT at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
2016-09-29T19:14:57.239-0400[App/0]OUT at org.apache.naming.resources.BaseDirContext.lookup(BaseDirContext.java:481)
2016-09-29T19:14:57.239-0400[App/0]OUT at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2016-09-29T19:14:57.239-0400[App/0]OUT at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-09-29T19:14:57.239-0400[App/0]OUTCaused by: javax.naming.NameNotFoundException: Resource container_customizer-1.0.0_RELEASE.jar not found
````

Any ideas?

**Comment by timeapen** [comment]
Issue was that the application was using an older version of Tomcat -  7.0.63.  Moving to a newer version, Tomcat gets us past this.
