### ISSUE TITLE
Cloud foundry issue while upgrading spring libraries with Build pack 3.9

### ISSUE THREAD

**Issue by pradeepkusingh** [cloudfoundry/java-buildpack#338]
We are trying to upgrade the spring libraries( Spring boot 1.4.1) on Diegeo(1.6) seeing some strange behavior. Same thing works fine locally, but in CF it fails. We are using Build pack 3.9 which support Spring boot 1.4 and above. Below is the error. I have already verified at multiple places and seeing this issue only in CF. Below  error is stopping us to go live 100% in prod. it looks like a class loading issue.

``` 
com.test.MongoDBConfiguration.mongoTemplate - Error occurred when creating the mongoTemplate.......ERROR_MESSAGE: Error creating bean with name 'mongoDbFactory' defined in class path resource [com/comcast/sparrow/activatorweb/repository/MongoDBConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.MongoDbFactory]: Factory method 'mongoDbFactory' threw exception; nested exception is java.lang.IllegalAccessError: tried to access method org.bson.types.ObjectId.<init>(III)V from class com.mongodb.Bytes ERROR_DETAILS: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDbFactory' defined in class path resource [com/comcast/sparrow/activatorweb/repository/MongoDBConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.mongodb.MongoDbFactory]: Factory method 'mongoDbFactory' threw exception; nested exception is java.lang.IllegalAccessError: tried to access method org.bson.types.ObjectId.<init>(III)V from class com.mongodb.Bytes
 at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1023)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
 at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
 at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
 at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:381)
 at com.comcast.sparrow.activatorweb.repository.MongoDBConfiguration$$EnhancerBySpringCGLIB$$bd6b329d.mongoDbFactory(<generated>)
 at com.comcast.sparrow.activatorweb.repository.MongoDBConfiguration.mongoTemplate(MongoDBConfiguration.java:68)
 at com.comcast.sparrow.activatorweb.repository.MongoDBConfiguration$$EnhancerBySpringCGLIB$$bd6b329d.CGLIB$mongoTemplate$0(<generated>)
 at com.comcast.sparrow.activatorweb.repository.MongoDBConfiguration$$EnhancerBySpringCGLIB$$bd6b329d$$FastClassBySpringCGLIB$$ecc75b5b.invoke(<generated>)
 at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
 at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
 at com.comcast.sparrow.activatorweb.repository.MongoDBConfiguration$$EnhancerBySpringCGLIB$$bd6b329d.mongoTemplate(<generated>)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
 at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
 at org.springframework
```

**Comment by nebhale** [comment]
Which version of the buildpack are you using?

**Comment by pradeepkusingh** [comment]
Build pack 3.9. yes. let me give you staging output. If I change the spring version to 1.3.7 or 1.2.8 same thing works fine.

**Comment by nebhale** [comment]
It would certainly appear that the problem is with your application's dependencies.  Notice that bit that says `tried to access method org.bson.types.ObjectId.<init>(III)V from class com.mongodb.Bytes `.  That looks certainly looks like the the MongoDB library is trying to access a type that isn't on the class path that you pushed to Cloud Foundry.  The buildpack doesn't contribute any of these dependencies.

**Comment by pradeepkusingh** [comment]
I would access above answer if same apps doesn't run locally. it runs without any issue. I made sure there is no multiple jars of monfo.

**Comment by nebhale** [comment]
I'm not sure what you expect out of the buildpack in this case as we don't contribute your MondoDB driver or any of it's dependencies.

**Comment by pradeepkusingh** [comment]
somehow I feel it is class loader issue. if this is not the right place , I can open a support ticket to CF directly.

**Comment by nebhale** [comment]
Opening a CF issue is probably a better avenue as the buildpack doesn't adjust classloaders when applications are started.

**Comment by pradeepkusingh** [comment]
ok, let me try. Thanks for help.
