### ISSUE TITLE
AllowLinkingAppl icationContextInitializer : Unsupported major.minor version 52.0 error

### ISSUE THREAD

**Issue by YunSangJun** [cloudfoundry/java-buildpack#343]
I use jdk 1.7.0.x on my java application.
When i push the app on CF using java-buildpack-online v3.9, following error is occur.

```
ERR Caused by: java.lang.UnsupportedClassVersionError: org/cloudfoundry/container/customizer/AllowLinkingApplicationContextInitializer : Unsupported major.minor version 52.0
```
In my opinion, the error is occured cause of compatibility between "java-buildpack-container-customizer" and jdk.
jdk : 1.7 
java-buildpack-container-customizer : compiled as 1.8
java-buildpack-container-customizer : https://github.com/cloudfoundry/java-buildpack-container-customizer

i attatch detail log.

```
2016-11-03T14:26:10.19+0900 [API/0]      OUT Updated app with guid 7d9b7636-bf1b-457b-8166-91abe0fa3d51 ({"state"=>"STARTED"})
2016-11-03T14:26:10.19+0900 [STG/0]      OUT Creating container
2016-11-03T14:26:10.60+0900 [STG/0]      OUT Successfully created container
2016-11-03T14:26:10.60+0900 [STG/0]      OUT Downloading app package...
2016-11-03T14:26:12.74+0900 [STG/0]      OUT Downloaded app package (44.6M)
2016-11-03T14:26:12.74+0900 [STG/0]      OUT Downloading buildpacks (java_buildpack), build artifacts cache...
2016-11-03T14:26:12.74+0900 [STG/0]      OUT Downloading java_buildpack...
2016-11-03T14:26:12.74+0900 [STG/0]      OUT Downloading build artifacts cache...
2016-11-03T14:26:12.81+0900 [STG/0]      OUT Downloaded java_buildpack
2016-11-03T14:26:15.43+0900 [STG/0]      OUT Downloaded build artifacts cache (123.3M)
2016-11-03T14:26:15.43+0900 [STG/0]      OUT Downloaded buildpacks
2016-11-03T14:26:15.43+0900 [STG/0]      OUT Staging...
2016-11-03T14:26:20.46+0900 [STG/0]      OUT -----> Java Buildpack Version: v3.9 | https://github.com/cloudfoundry/java-buildpack.git#b050954
2016-11-03T14:26:22.76+0900 [STG/0]      OUT -----> Downloading Open Jdk JRE 1.7.0_79 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_
64/openjdk-1.7.0_79.tar.gz (found in cache)
2016-11-03T14:26:24.02+0900 [STG/0]      OUT        Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.2s)
2016-11-03T14:26:25.20+0900 [STG/0]      OUT -----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry
.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
2016-11-03T14:26:25.24+0900 [STG/0]      OUT        Memory Settings: -Xmx681574K -XX:MaxPermSize=104857K -Xss349K -Xms681574K -XX:PermSize=104857K
2016-11-03T14:26:26.35+0900 [STG/0]      OUT -----> Downloading Container Customizer 1.0.0_RELEASE from https://java-buildpack.cloudfoundry.org/contai
ner-customizer/container-customizer-1.0.0_RELEASE.jar (found in cache)
2016-11-03T14:26:27.27+0900 [STG/0]      OUT -----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://java-buildpack.cloudfoundry.or
g/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
2016-11-03T14:26:49.40+0900 [STG/0]      OUT Exit status 0
2016-11-03T14:26:49.40+0900 [STG/0]      OUT Staging complete
2016-11-03T14:26:49.40+0900 [STG/0]      OUT Uploading droplet, build artifacts cache...
2016-11-03T14:26:49.40+0900 [STG/0]      OUT Uploading droplet...
2016-11-03T14:26:49.40+0900 [STG/0]      OUT Uploading build artifacts cache...
2016-11-03T14:26:52.89+0900 [STG/0]      OUT Uploaded build artifacts cache (123.3M)
2016-11-03T14:26:54.46+0900 [STG/0]      OUT Uploaded droplet (81M)
2016-11-03T14:26:54.48+0900 [STG/0]      OUT Uploading complete
2016-11-03T14:26:56.13+0900 [CELL/0]     OUT Creating container
2016-11-03T14:26:56.59+0900 [CELL/0]     OUT Successfully created container
2016-11-03T14:27:02.48+0900 [HEALTH/0]   OUT healthcheck failed
2016-11-03T14:27:02.48+0900 [HEALTH/0]   OUT Exit status 1
2016-11-03T14:27:02.82+0900 [APP/0]      ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.lang.reflect.Method.invoke(Method.java:606)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.A
pplicationContextInitializer : org.cloudfoundry.container.customizer.AllowLinkingApplicationContextInitializer
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:42
4)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:403)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:394)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:261)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:237)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at io.ghama.cna.sample.Application.main(Application.java:24)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    ... 8 more
2016-11-03T14:27:02.82+0900 [APP/0]      ERR Caused by: java.lang.UnsupportedClassVersionError: org/cloudfoundry/container/customizer/AllowLinkingAppl
icationContextInitializer : Unsupported major.minor version 52.0
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.lang.ClassLoader.defineClass1(Native Method)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.security.AccessController.doPrivileged(Native Method)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:89)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:41
6)
2016-11-03T14:27:02.82+0900 [APP/0]      ERR    ... 15 more
2016-11-03T14:27:02.84+0900 [APP/0]      OUT Exit status 1
2016-11-03T14:27:02.85+0900 [CELL/0]     OUT Exit status 0
2016-11-03T14:27:02.89+0900 [API/0]      OUT App instance exited with guid 7d9b7636-bf1b-457b-8166-91abe0fa3d51 payload: {"instance"=>"1a138928-6435-4
492-6c86-b49dfe95584a", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1
\n* cancelled\n* cancelled", "crash_count"=>1, "crash_timestamp"=>1478150822846017811, "version"=>"ef184210-ff07-4185-9f8c-e09c568b251a"}
```

**Comment by nebhale** [comment]
Resolved by https://github.com/cloudfoundry/java-buildpack-container-customizer/commit/4be73fee7f9bdb538c6be5ddcff49b2b2b85bc40
