### ISSUE TITLE
Tomcat version pinning bug

### ISSUE THREAD

**Issue by combor** [cloudfoundry/java-buildpack#355]
## What

Tested with versions: 3.9 and 3.10 

Java buildpack downloads dependencies over HTTP from https://github.com/cloudfoundry/java-buildpack/blob/v3.9/config/repository.yml#L18
The version pinning is done here: https://github.com/cloudfoundry/java-buildpack/blob/v3.9/config/tomcat.yml#L19

But in reality what it downloads is:

```
2016-11-29T11:24:15.39+0000 [STG/0]      OUT -----> Java Buildpack Version: v3.9 | https://github.com/cloudfoundry/java-buildpack.git#b050954
2016-11-29T11:24:16.07+0000 [STG/0]      OUT -----> Downloading Open Jdk JRE 1.8.0_101 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_101.tar.gz (0
.4s)
2016-11-29T11:24:17.11+0000 [STG/0]      OUT        Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.0s)
2016-11-29T11:24:17.15+0000 [STG/0]      OUT -----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x
86_64/memory-calculator-2.0.2_RELEASE.tar.gz (0.0s)
2016-11-29T11:24:17.17+0000 [STG/0]      OUT        Memory Settings: -Xss349K -Xmx681574K -XX:MaxMetaspaceSize=104857K -Xms681574K -XX:MetaspaceSize=104857K
2016-11-29T11:24:17.29+0000 [STG/0]      OUT -----> Downloading Tomcat Instance 8.0.39 from https://java-buildpack.cloudfoundry.org/tomcat/tomcat-8.0.39.tar.gz (0.1s)
```

So the tomcat version that is pinned is not beeing used but the latest `micro` version is selected. That means there is a bug in version selection code which I couldn't find.

We know that java-buildpack 3.9 doesn't pin tomcat version correctly. Tomcat starting from 8.0.39 has changed which characters are allowed in URL: https://github.com/apache/tomcat80/commit/779d5d34e68e50d2f721897050b147106992f566

That makes cf-acceptance-tests to fail here: https://github.com/cloudfoundry/cf-acceptance-tests/blob/45bb64e9c24659e9a1be1004a9664dfc0b7c62c9/apps/encoding.go#L62 as Tomcat returns `400` failing to parse special characters. 

```
[2016-11-29 11:15:14.53 (UTC)]> cf logs CATS-2-APP-54ff0e0e-857d-4966-7 --recent 
Connected, dumping recent logs for app CATS-2-APP-54ff0e0e-857d-4966-7 in org CATS-2-ORG-2e3f292f-cb87-4ba6-6 / space CATS-2-SPACE-58c1b1a0-ec15-47b4-5 as CATS-USER-2-2016_11_29-11h11m48.68s...

2016-11-29T11:15:07.71+0000 [RTR/0]      OUT CATS-2-APP-54ff0e0e-857d-4966-7.piotr-dev.dev.cloudpipelineapps.digital - [29/11/2016:11:15:07.710 +0000] "GET /requesturi/!~^'()$"?!'()$ HTTP/1.1" 400 0 0 "-" "curl/7.26.0" 127.0.0.1:20524 x_forwarded_for:"52.213.194.159, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:9b122ee1-df34-4650-4236-180c165c8d2c response_time:0.00149284 app_id:0bc35bd4-2ff8-465e-a9ff-ac7444ccf0b3 app_index:0
2016-11-29T11:15:07.74+0000 [RTR/1]      OUT CATS-2-APP-54ff0e0e-857d-4966-7.piotr-dev.dev.cloudpipelineapps.digital - [29/11/2016:11:15:07.742 +0000] "GET /requesturi/!~^'()$"?!'()$ HTTP/1.1" 400 0 0 "-" "curl/7.26.0" 127.0.0.1:7692 x_forwarded_for:"52.213.194.159, 127.0.0.1" x_forwarded_proto:"https" vcap_request_id:1c5504a1-904a-41ac-734e-538be91ae9e5 response_time:0.002117765 app_id:0bc35bd4-2ff8-465e-a9ff-ac7444ccf0b3 app_index:0
```

And app logs show:

```
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT [CONTAINER] org.apache.coyote.http11.Http11NioProcessor        INFO    Error parsing HTTP request header
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT  Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT         at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:283)
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT         at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1017)
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT         at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2016-11-29T14:17:35.31+0000 [APP/PROC/WEB/0]OUT         at java.lang.Thread.run(Thread.java:745)
```

**Comment by nebhale** [comment]
Just pushed an application using v3.6 and it appears to have behaved properly for me
with `v3.9` downloading `8.0.36` and `v3.10` downloading `8.0.38`.

```
zapp master: cf push -b https://github.com/cloudfoundry/java-buildpack.git#v3.9
Using manifest file /Users/bhale/dev/sources/java-test-applications/web-application/manifest.yml

Using stack cflinuxfs2...
OK
Updating app web-application in org bhale / space development as bhale@pivotal.io...
OK

Uploading web-application...
Uploading app files from: /var/folders/t_/ydt4f_tj27j9_z2k2j8129780000gn/T/unzipped-app096524453
Uploading 178.8K, 23 files
Done uploading               
OK

Stopping app web-application in org bhale / space development as bhale@pivotal.io...
OK

Starting app web-application in org bhale / space development as bhale@pivotal.io...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (15.5M)
Downloading build artifacts cache...
Downloaded build artifacts cache (465.8M)
Staging...
-----> Java Buildpack Version: v3.9 | https://github.com/cloudfoundry/java-buildpack.git#ed26f2b
-----> Downloading Open Jdk JRE 1.8.0_101 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_101.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.1s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
       Memory Settings: -Xmx681574K -XX:MaxMetaspaceSize=104857K -Xss349K -Xms681574K -XX:MetaspaceSize=104857K
-----> Downloading Container Customizer 1.0.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-customizer/container-customizer-1.0.0_RELEASE.jar (found in cache)
-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
-----> Downloading Tomcat Instance 8.0.36 from https://java-buildpack.cloudfoundry.org/tomcat/tomcat-8.0.36.tar.gz (1.0s)
       Expanding Tomcat Instance to .java-buildpack/tomcat (0.1s)
-----> Downloading Tomcat Logging Support 2.5.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-logging-support/tomcat-logging-support-2.5.0_RELEASE.jar (found in cache)
-----> Downloading Tomcat Access Logging Support 2.5.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-access-logging-support/tomcat-access-logging-support-2.5.0_RELEASE.jar (found in cache)
-----> Downloading Tomcat Lifecycle Support 2.5.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-lifecycle-support/tomcat-lifecycle-support-2.5.0_RELEASE.jar (found in cache)
Exit status 0
Staging complete
```

```
zapp master: cf push -b https://github.com/cloudfoundry/java-buildpack.git#v3.10
Using manifest file /Users/bhale/dev/sources/java-test-applications/web-application/manifest.yml

Using stack cflinuxfs2...
OK
Updating app web-application in org bhale / space development as bhale@pivotal.io...
OK

Uploading web-application...
Uploading app files from: /var/folders/t_/ydt4f_tj27j9_z2k2j8129780000gn/T/unzipped-app115057190
Uploading 178.8K, 23 files
Done uploading               
OK

Stopping app web-application in org bhale / space development as bhale@pivotal.io...
OK

Starting app web-application in org bhale / space development as bhale@pivotal.io...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (15.5M)
Downloading build artifacts cache...
Downloaded build artifacts cache (474.6M)
Staging...
-----> Java Buildpack Version: v3.10 | https://github.com/cloudfoundry/java-buildpack.git#59f4880
-----> Downloading Open Jdk JRE 1.8.0_111 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_111.tar.gz (found in cache)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.2s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
       Memory Settings: -Xss349K -Xmx681574K -XX:MaxMetaspaceSize=104857K -Xms681574K -XX:MetaspaceSize=104857K
-----> Downloading Container Customizer 1.0.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-customizer/container-customizer-1.0.0_RELEASE.jar (found in cache)
-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
-----> Downloading Tomcat Instance 8.0.38 from https://java-buildpack.cloudfoundry.org/tomcat/tomcat-8.0.38.tar.gz (found in cache)
       Expanding Tomcat Instance to .java-buildpack/tomcat (0.1s)
-----> Downloading Tomcat Lifecycle Support 2.5.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-lifecycle-support/tomcat-lifecycle-support-2.5.0_RELEASE.jar (found in cache)
-----> Downloading Tomcat Logging Support 2.5.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-logging-support/tomcat-logging-support-2.5.0_RELEASE.jar (found in cache)
-----> Downloading Tomcat Access Logging Support 2.5.0_RELEASE from https://java-buildpack.cloudfoundry.org/tomcat-access-logging-support/tomcat-access-logging-support-2.5.0_RELEASE.jar (found in cache)
Exit status 0
Staging complete
```

**Comment by combor** [comment]
So that's interesting why there is such difference in behaviour between our environments.
Our manifest can be found here: https://github.com/alphagov/paas-cf/tree/master/manifests/cf-manifest/manifest

**Comment by nebhale** [comment]
If I had to guess, it's because you're using the online buildpack instead of the offline one.  The online buildpack, in addition to gathering dependencies from the internet, is intentionally not version pinned.  The goal of that buildpack is to be as up-to-date as possible.  I believe that if you push using `java-buildpack-offline` (not sure when the buildpacks team changed the name, so you might need to use the older name), you'll find that it pins versions appropriately.

**Comment by combor** [comment]
@nebhale Just checked that. You are right. The default java buildpack appears to be `online`. I have changed it to offline version and now acceptance-tests are ok as tomcat version is back to 8.0.36 but it's strange decision to make online version  the default one. I'll close this issue.

**Comment by combor** [comment]
BTW @nebhale thank's for pointing this as it helped us a lot.

**Comment by nebhale** [comment]
@combor Well, we do generally want customers using the online buildpack where possible (note that the default is different in PCF) as it's the most "secure by default".  We want users using the latest possible versions of the dependencies without any explicit user action.

**Comment by combor** [comment]
Well, as it turns out it can lead to unexpected behaviours like in this case.
