### ISSUE TITLE
Staging failure using JRE 1.7 (UnsupportedClassVersionError in ContainerCertificateTrustStoreBuilder)

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/java-buildpack#369]
Master (https://github.com/cloudfoundry/java-buildpack/tree/6f25b7e38a09188c9aeb2ff4f26dbbbaa8fdde5e) seems to fail staging when users specify JRE 1.7:

```
-----> Downloaded app package (42M)


Cloning into '/tmp/buildpacks/java-buildpack'...


-----> Java Buildpack Version: 6f25b7e | https://github.com/cloudfoundry/java-buildpack.git#6f25b7e
-----> Downloading Open Jdk JRE 1.7.0_79 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.7.
0_79.tar.gz (0.4s)
       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (0.9s)
-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-cal
culator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (0.0s)
       Memory Settings: -XX:MaxPermSize=209715K -Xss699K -Xmx1363148K -Xms1363148K -XX:PermSize=209715K
-----> Downloading Container Certificate Trust Store 1.0.0_RELEASE from https://java-buildpack.cloudfoundry.org/containe
r-certificate-trust-store/container-certificate-trust-store-1.0.0_RELEASE.jar (0.0s)
       Adding certificates to .java-buildpack/container_certificate_trust_store/truststore.jks
Command '/tmp/staged/app/.java-buildpack/open_jdk_jre/bin/java -jar /tmp/staged/app/.java-buildpack/container_certificat
e_trust_store/container_certificate_trust_store-1.0.0_RELEASE.jar /etc/ssl/certs/ca-certificates.crt /tmp/staged/app/.ja
va-buildpack/container_certificate_trust_store/truststore.jks java-buildpack-trust-store-password' has failed
STDOUT:
STDERR: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/cloudfoundry/certificate/ContainerCertificateTrustStoreBuilder : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
[Buildpack]                      ERROR Compile failed with exception RuntimeError
Staging failed: Buildpack compilation step failed
```

By a cursory look it may be that https://github.com/cloudfoundry/java-buildpack/commit/1185f8c279d714d99da35b86974874ee63ee19d2 is affected by the same problem that was affecting the container customizer (https://github.com/cloudfoundry/java-buildpack/issues/343)

**Comment by CAFxX** [comment]
We're verifying if v3.11 is unaffected

**Comment by CAFxX** [comment]
v3.11 is unaffected

**Comment by nebhale** [comment]
Yep, let me make it 1.7 compatible.  😢

**Comment by nebhale** [comment]
Resolved by https://github.com/cloudfoundry/java-buildpack-container-certificate-trust-store/commit/9d391bb5942ec9520a37975449733bd8ae8518b4
