### ISSUE TITLE
I am trying to deploy magento open source on bluemix, but i getting Buildpack error in cloud foundry, any help?

### ISSUE THREAD

**Issue by nguyenthitrang** [cloudfoundry/java-buildpack#413]
```
Creating container
Successfully created container
Downloading app package...
Downloaded app package (226.1M)
Downloading build artifacts cache...
Downloaded build artifacts cache (109B)
Staging...
-------> Buildpack version 4.3.10
Traceback (most recent call last):
  File "/tmp/buildpacks/027188c1468d949df6631372dafec9b3/scripts/compile.py", li
ne 50, in <module>
  File "/tmp/buildpacks/027188c1468d949df6631372dafec9b3/lib/build_pack_utils/bu
ilder.py", line 242, in done
    process_extension(extn, self._builder._ctx, 'configure', process)
  File "/tmp/buildpacks/027188c1468d949df6631372dafec9b3/lib/build_pack_utils/ut
ils.py", line 69, in process_extension
    success(getattr(extn, to_call)(*args))
  File "/tmp/buildpacks/027188c1468d949df6631372dafec9b3/extensions/composer/ext
ension.py", line 117, in read_version_from_composer
    composer = json.load(open(json_path, 'r'))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
    .from_build_pack('lib/additional_commands')
  File "/tmp/buildpacks/027188c1468d949df6631372dafec9b3/extensions/composer/ext
ension.py", line 387, in configure
    config.configure()
  File "/tmp/buildpacks/027188c1468d949df6631372dafec9b3/extensions/composer/ext
ension.py", line 139, in configure
    php_version = self.read_version_from_composer('php')
    **kw)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 12 column 9 (char 272)
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container

FAILED
Error restarting application: BuildpackCompileFailed
```

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
