### ISSUE TITLE
Failing tests for tagv4.0

### ISSUE THREAD

**Issue by mehrotra-prateek** [cloudfoundry/java-buildpack#428]
Hello,

I am trying to compile, test and deploy v4.0 tag of the buildpack. To do so, I have done following
1. clone repository
1. rvm use ruby-2.2.7
1. bundle install
1. bundle exec rake`

The above results in 7 test failures. Any guidance on how to fix them will be appreciated.

Failures
```
Failures:

  1) JavaBuildpack::Jre::OpenJDKLikeMemoryCalculator creates memory calculation command without vm options specified
     Failure/Error:
       expect(command).to eq('CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_like_memory_calculator/bin/' \
                               'java-buildpack-memory-calculator-0.0.0 -totMemory=$MEMORY_LIMIT -stackThreads=200 ' \
                               '-loadedClasses=2 -poolType=metaspace) && echo JVM Memory Configuration: ' \
                               '$CALCULATED_MEMORY')

       expected: "CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_like_memory_calculator/bin/java-buildpack-memory-c...eads=200 -loadedClasses=2 -poolType=metaspace) && echo JVM Memory Configuration: $CALCULATED_MEMORY"
            got: "CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_like_memory_calculator/bin/java-buildpack-memory-c...e -vmOptions='-Dhttp.nonProxyHosts=localhost') && echo JVM Memory Configuration: $CALCULATED_MEMORY"

       (compared using ==)
     # ./spec/java_buildpack/jre/open_jdk_like_memory_calculator_spec.rb:92:in `block (2 levels) in <top (required)>'

  2) JavaBuildpack::Jre::OpenJDKLike returns command for Java 8
     Failure/Error:
       expect(component.command).to eq('CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_like/bin/' \
                                       'java-buildpack-memory-calculator-0.0.0 -totMemory=$MEMORY_LIMIT' \
                                       ' -stackThreads=200 -loadedClasses=0 -poolType=metaspace) && echo JVM Memory ' \
                                       'Configuration: $CALCULATED_MEMORY')

       expected: "CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_like/bin/java-buildpack-memory-calculator-0.0.0 -t...eads=200 -loadedClasses=0 -poolType=metaspace) && echo JVM Memory Configuration: $CALCULATED_MEMORY"
            got: "CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_like/bin/java-buildpack-memory-calculator-0.0.0 -t...e -vmOptions='-Dhttp.nonProxyHosts=localhost') && echo JVM Memory Configuration: $CALCULATED_MEMORY"

       (compared using ==)
     # ./spec/java_buildpack/jre/open_jdk_like_spec.rb:76:in `block (2 levels) in <top (required)>'

  3) JavaBuildpack::Jre::OpenJDKLike returns command for Java 7
     Failure/Error:
       expect(component.command).to eq('CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_like/bin/' \
                                       'java-buildpack-memory-calculator-0.0.0 -totMemory=$MEMORY_LIMIT' \
                                       ' -stackThreads=200 -loadedClasses=0 -poolType=permgen) && echo JVM Memory ' \
                                       'Configuration: $CALCULATED_MEMORY')

       expected: "CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_like/bin/java-buildpack-memory-calculator-0.0.0 -t...hreads=200 -loadedClasses=0 -poolType=permgen) && echo JVM Memory Configuration: $CALCULATED_MEMORY"
            got: "CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_like/bin/java-buildpack-memory-calculator-0.0.0 -t...n -vmOptions='-Dhttp.nonProxyHosts=localhost') && echo JVM Memory Configuration: $CALCULATED_MEMORY"

       (compared using ==)
     # ./spec/java_buildpack/jre/open_jdk_like_spec.rb:67:in `block (2 levels) in <top (required)>'

  4) JavaBuildpack::Framework::ContainerCertificateTrustStore detects with ca-certificates file
     Failure/Error: expect(component.detect).to eq('container-certificate-trust-store=0.0.0')

       expected: "container-certificate-trust-store=0.0.0"
            got: nil

       (compared using ==)
     # ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:32:in `block (2 levels) in <top (required)>'

  5) JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore
     Failure/Error: print "-----> Downloading #{name} #{version} from #{uri.sanitize_uri} "

     NoMethodError:
       undefined method `sanitize_uri' for nil:NilClass
     # ./lib/java_buildpack/component/base_component.rb:90:in `download'
     # ./lib/java_buildpack/component/base_component.rb:107:in `download_jar'
     # ./lib/java_buildpack/component/versioned_dependency_component.rb:69:in `download_jar'
     # ./lib/java_buildpack/framework/container_certificate_trust_store.rb:29:in `compile'
     # ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:55:in `block (2 levels) in <top (required)>'

  6) JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore with jre source
     Failure/Error: print "-----> Downloading #{name} #{version} from #{uri.sanitize_uri} "

     NoMethodError:
       undefined method `sanitize_uri' for nil:NilClass
     # ./lib/java_buildpack/component/base_component.rb:90:in `download'
     # ./lib/java_buildpack/component/base_component.rb:107:in `download_jar'
     # ./lib/java_buildpack/component/versioned_dependency_component.rb:69:in `download_jar'
     # ./lib/java_buildpack/framework/container_certificate_trust_store.rb:29:in `compile'
     # ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:74:in `block (2 levels) in <top (required)>'

  7) JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore with server jre source
     Failure/Error: print "-----> Downloading #{name} #{version} from #{uri.sanitize_uri} "

     NoMethodError:
       undefined method `sanitize_uri' for nil:NilClass
     # ./lib/java_buildpack/component/base_component.rb:90:in `download'
     # ./lib/java_buildpack/component/base_component.rb:107:in `download_jar'
     # ./lib/java_buildpack/component/versioned_dependency_component.rb:69:in `download_jar'
     # ./lib/java_buildpack/framework/container_certificate_trust_store.rb:29:in `compile'
     # ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:93:in `block (2 levels) in <top (required)>'

Finished in 40.72 seconds (files took 0.60344 seconds to load)
680 examples, 7 failures

Failed examples:

rspec ./spec/java_buildpack/jre/open_jdk_like_memory_calculator_spec.rb:85 # JavaBuildpack::Jre::OpenJDKLikeMemoryCalculator creates memory calculation command without vm options specified
rspec ./spec/java_buildpack/jre/open_jdk_like_spec.rb:74 # JavaBuildpack::Jre::OpenJDKLike returns command for Java 8
rspec ./spec/java_buildpack/jre/open_jdk_like_spec.rb:65 # JavaBuildpack::Jre::OpenJDKLike returns command for Java 7
rspec ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:29 # JavaBuildpack::Framework::ContainerCertificateTrustStore detects with ca-certificates file
rspec ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:45 # JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore
rspec ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:58 # JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore with jre source
rspec ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:77 # JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore with server jre source
```

**Comment by nebhale** [comment]
All of the errors appear to be related to an existing `JAVA_OPTS` environment variable.  If you unset that (the tests assume a clean environment), then they should pass.

**Comment by mehrotra-prateek** [comment]
Thanks the first 3 are gone but not the certificate ones. But am guessing its about getting clean environment. May be will try to get a clean docker image and run tests there.
