### ISSUE TITLE
build pack tests for ContainerCertificateTrustStore do not work

### ISSUE THREAD

**Issue by pivotal-Jammy-Louie** [cloudfoundry/java-buildpack#433]
The stubs in the tests  `container_certificate_trust_store_spec.rb` do not work.

In `include_context component_helper`, the ContainerCertificateTrustStore component is already created in the initialize and thus the following lines don't actually do anything since the component is already created.

```
let(:ca_certificates) { Pathname.new('spec/fixtures/ca-certificates.crt') }
allow(component).to receive(:ca_certificates).and_return(ca_certificates)
```

It looks like the tests use the default cert path: `/etc/ssl/cert.pem` instead of the `ca_certificates` fixture.

**Comment by nebhale** [comment]
What makes you think this is true?  The test code passes on multiple platforms, some of which don't have `/etc/ssl/cert.pem`.  The `let()` in classes that `include_context` override the behavior in the helper itself.

**Comment by bsnchan** [comment]
@nebhale One of our workstation didn't have the `/etc/ssl/cert.pem` file on it and the specs were failing. You can easily test this by just temporarily moving the file:

```
ruby 2.0.0p648 (system) dx212 in ~/workspace/java-buildpack
± bc+jl |ssc-gemfire U:1 ✗| → ls -l /etc/ssl/cert.pem
-rw-r--r--  1 root  wheel  227344  9 Feb 20:47 /etc/ssl/cert.pem

ruby 2.0.0p648 (system) dx212 in ~/workspace/java-buildpack
± bc+jl |ssc-gemfire U:1 ✗| → sudo mv /etc/ssl/cert.pem /etc/ssl/cert.pem.old
Password:

ruby 2.3.3p222 dx212 in ~/workspace/java-buildpack
± bc+jl |ssc-gemfire U:1 ✗| → be rake spec
/Users/pivotal/.rubies/2.3.3/bin/ruby -I/Users/pivotal/.gem/ruby/2.3.3/gems/rspec-core-3.6.0/lib:/Users/pivotal/.gem/ruby/2.3.3/gems/rspec-support-3.6.0/lib /Users/pivotal/.gem/ruby/2.3.3/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 19874
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F.FFF.....................................................

Failures:

  1) JavaBuildpack::Framework::ContainerCertificateTrustStore detects with ca-certificates file
     Failure/Error: expect(component.detect).to eq('container-certificate-trust-store=0.0.0')

       expected: "container-certificate-trust-store=0.0.0"
            got: nil

       (compared using ==)
     # ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:31:in `block (2 levels) in <top (required)>'

  2) JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore with jre source
     Failure/Error: print "-----> Downloading #{name} #{version} from #{uri.sanitize_uri} "

     NoMethodError:
       undefined method `sanitize_uri' for nil:NilClass
     # ./lib/java_buildpack/component/base_component.rb:89:in `download'
     # ./lib/java_buildpack/component/base_component.rb:106:in `download_jar'
     # ./lib/java_buildpack/component/versioned_dependency_component.rb:68:in `download_jar'
     # ./lib/java_buildpack/framework/container_certificate_trust_store.rb:28:in `compile'
     # ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:73:in `block (2 levels) in <top (required)>'

  3) JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore
     Failure/Error: print "-----> Downloading #{name} #{version} from #{uri.sanitize_uri} "

     NoMethodError:
       undefined method `sanitize_uri' for nil:NilClass
     # ./lib/java_buildpack/component/base_component.rb:89:in `download'
     # ./lib/java_buildpack/component/base_component.rb:106:in `download_jar'
     # ./lib/java_buildpack/component/versioned_dependency_component.rb:68:in `download_jar'
     # ./lib/java_buildpack/framework/container_certificate_trust_store.rb:28:in `compile'
     # ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:54:in `block (2 levels) in <top (required)>'

  4) JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore with server jre source
     Failure/Error: print "-----> Downloading #{name} #{version} from #{uri.sanitize_uri} "

     NoMethodError:
       undefined method `sanitize_uri' for nil:NilClass
     # ./lib/java_buildpack/component/base_component.rb:89:in `download'
     # ./lib/java_buildpack/component/base_component.rb:106:in `download_jar'
     # ./lib/java_buildpack/component/versioned_dependency_component.rb:68:in `download_jar'
     # ./lib/java_buildpack/framework/container_certificate_trust_store.rb:28:in `compile'
     # ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:92:in `block (2 levels) in <top (required)>'

Finished in 11.91 seconds (files took 0.72423 seconds to load)
689 examples, 4 failures

Failed examples:

rspec ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:28 # JavaBuildpack::Framework::ContainerCertificateTrustStore detects with ca-certificates file
rspec ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:57 # JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore with jre source
rspec ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:44 # JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore
rspec ./spec/java_buildpack/framework/container_certificate_trust_store_spec.rb:76 # JavaBuildpack::Framework::ContainerCertificateTrustStore creates truststore with server jre source
```

**Comment by nebhale** [comment]
Ah, yeah now I see.  That `allow` call needs to be moved into a `before` block to get access to the proper bit of the lifecycle.  However, given that the `ContainerCertificateTrustStore` has been removed in the latest development lines (in lieu of the `ContainerCertificateSecurityProvider`), there's no fix to be made here.
