### ISSUE TITLE
Spring App startup error on cloud foundry

### ISSUE THREAD

**Issue by usherfu** [cloudfoundry/java-buildpack#450]
Hi, 

I was trying to deploy [nGrinder controller 3.4 ](https://github.com/naver/ngrinder/tree/ngrinder-3.4) to Cloud Foundry,  corresponding pom.xml file is [here](https://github.com/naver/ngrinder/blob/ngrinder-3.4/ngrinder-controller/pom.xml) which references its parent [pom.xml](https://github.com/naver/ngrinder/blob/ngrinder-3.4/pom.xml)

however, following error showed in the app logs:

C

```
OUT j**ava.lang.NoClassDefFoundError: org/springframework/context/ApplicationContextInitializer**
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_121]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_121]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_121]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_121]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_121]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_121]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_121]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_121]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_121]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:450) ~[na:na]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:403) ~[na:na]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at org.springframework.util.ClassUtils.forName(ClassUtils.java:250) ~[spring-core-4.2.5.RELEASE.jar:4.2.5.RELEASE]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at org.springframework.web.context.ContextLoader.loadInitializerClass(ContextLoader.java:519) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at org.springframework.web.context.ContextLoader.determineContextInitializerClasses(ContextLoader.java:509) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at org.springframework.web.context.ContextLoader.customizeContext(ContextLoader.java:466) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
2017-06-23T00:49:28.79+0200 [APP/PROC/WEB/0]OUT         at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
```

Altough issue #406 shows the same error, and I have tried with latest java buildpack, the issue persists.  Any idea is appreciated?

**Comment by usherfu** [comment]
Also tried to push a WAR without Main-class by following this [issue](https://github.com/cloudfoundry/cli/issues/725), got different error.

**Comment by nebhale** [comment]
That error message implies that your Spring application cannot find the `org.springframework.context.ApplicationContextInitializer` which is found in the `spring-context` JAR.  The `spring-web` jar is attempting to `loadInitializerClass`, but when that class is loaded, it's parent class (the `ApplicationContextInitializer`) is not available to it.

**Comment by nebhale** [comment]
Since there’s been no response on this issue in a couple of weeks, I’m going to close it.  If you’d like to see it re-opened, please comment on the issue and I’ll reopen it.
