### ISSUE TITLE
Session replication support?

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/java-buildpack#453]
Hi team:
 I looked at some of the previous questions,previously support session replication?
But now do not support it? If I do not want to use spring session achieve, it can also be used to automatically for buildpack?

**Comment by geekyzk** [comment]
This is my a simple pedis instance
```
 "mongodb": [
   {
    "credentials": {
     "host": "192.168.4.103",
     "password": "ybuDlLj0Se0vJEp6NDEjYQAyliNB0F5t",
     "port": "6379",
     "tag": "session-replication"
    },
    "label": "mongodb",
    "name": "test",
    "plan": "default",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "session-replication",
     "session-replication-1"
    ]
   }
  ]
```
you can ignore mongod,it face reds ,

when my app is not bound the instances, it can running
but bind this instance, the app is not running, it throws:

```
 2017-06-27T17:58:21.95+0800 [CELL/0] OUT Creating container
   2017-06-27T17:58:22.32+0800 [CELL/0] OUT Successfully created container
   2017-06-27T17:58:22.35+0800 [CELL/1] OUT Successfully created container
   2017-06-27T17:58:24.79+0800 [CELL/0] OUT Starting health monitoring of container
   2017-06-27T17:58:24.85+0800 [CELL/1] OUT Starting health monitoring of container
   2017-06-27T17:58:26.33+0800 [APP/0] OUT   '  |____| .__|_| |_|_| |_\__, | / / / /
   2017-06-27T17:58:26.33+0800 [APP/0] OUT  =========|_|==============|___/=/_/_/_/
   2017-06-27T17:58:26.33+0800 [APP/0] OUT   .   ____          _            __ _ _
   2017-06-27T17:58:26.33+0800 [APP/0] OUT  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
   2017-06-27T17:58:26.33+0800 [APP/0] OUT ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
   2017-06-27T17:58:26.33+0800 [APP/0] OUT  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
   2017-06-27T17:58:26.34+0800 [APP/0] OUT  :: Spring Boot ::        (v1.5.4.RELEASE)
   2017-06-27T17:58:26.49+0800 [APP/0] OUT 2017-06-27 09:58:26.487  INFO 19 --- [           main] pertySourceApplicationContextInitializer : Adding 'cloud' PropertySource to ApplicationContext
   2017-06-27T17:58:26.50+0800 [APP/1] OUT  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
   2017-06-27T17:58:26.50+0800 [APP/1] OUT   .   ____          _            __ _ _
   2017-06-27T17:58:26.50+0800 [APP/1] OUT  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
   2017-06-27T17:58:26.50+0800 [APP/1] OUT ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
   2017-06-27T17:58:26.50+0800 [APP/1] OUT  =========|_|==============|___/=/_/_/_/
   2017-06-27T17:58:26.50+0800 [APP/1] OUT   '  |____| .__|_| |_|_| |_\__, | / / / /
   2017-06-27T17:58:26.50+0800 [APP/1] OUT  :: Spring Boot ::        (v1.5.4.RELEASE)
   2017-06-27T17:58:26.64+0800 [APP/1] OUT 2017-06-27 09:58:26.643  INFO 25 --- [           main] pertySourceApplicationContextInitializer : Adding 'cloud' PropertySource to ApplicationContext
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at java.net.URI$Parser.parse(URI.java:3042) ~[na:1.8.0_101]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 2017-06-27 09:58:26.655 ERROR 19 --- [           main] o.s.boot.SpringApplication               : Application startup failed
   2017-06-27T17:58:26.65+0800 [APP/0] OUT java.lang.NullPointerException: null
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.UriBasedServiceInfo.<init>(UriBasedServiceInfo.java:26) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.common.MongoServiceInfo.<init>(MongoServiceInfo.java:21) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_101]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.UriInfo.getUri(UriInfo.java:89) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.UriInfo.<init>(UriInfo.java:47) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.StandardUriInfoFactory.createUri(StandardUriInfoFactory.java:17) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.MongoServiceInfoCreator.createServiceInfo(MongoServiceInfoCreator.java:24) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.AbstractCloudConnector.getServiceInfos(AbstractCloudConnector.java:40) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.MongoServiceInfoCreator.createServiceInfo(MongoServiceInfoCreator.java:12) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.AbstractCloudConnector.getServiceInfo(AbstractCloudConnector.java:61) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getServiceInfos(Cloud.java:89) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getCloudProperties(Cloud.java:209) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.spring.CloudPropertySourceApplicationContextInitializer.addCloudPropertySource(CloudPropertySourceApplicationContextInitializer.java:83) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.cloudfoundry.reconfiguration.spring.CloudPropertySourceApplicationContextInitializer.initialize(CloudPropertySourceApplicationContextInitializer.java:67) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at com.ttaocloud.SessionRedisApplication.main(SessionRedisApplication.java:10) [classes/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [app/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [app/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [app/:na]
   2017-06-27T17:58:26.65+0800 [APP/0] OUT 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [app/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at java.net.URI$Parser.parse(URI.java:3042) ~[na:1.8.0_101]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 2017-06-27 09:58:26.744 ERROR 25 --- [           main] o.s.boot.SpringApplication               : Application startup failed
   2017-06-27T17:58:26.74+0800 [APP/1] OUT java.lang.NullPointerException: null
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.UriBasedServiceInfo.<init>(UriBasedServiceInfo.java:26) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.common.MongoServiceInfo.<init>(MongoServiceInfo.java:21) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_101]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.UriInfo.getUri(UriInfo.java:89) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.UriInfo.<init>(UriInfo.java:47) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.util.StandardUriInfoFactory.createUri(StandardUriInfoFactory.java:17) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.MongoServiceInfoCreator.createServiceInfo(MongoServiceInfoCreator.java:24) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getCloudProperties(Cloud.java:209) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.spring.CloudPropertySourceApplicationContextInitializer.addCloudPropertySource(CloudPropertySourceApplicationContextInitializer.java:83) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.cloudfoundry.MongoServiceInfoCreator.createServiceInfo(MongoServiceInfoCreator.java:12) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.AbstractCloudConnector.getServiceInfo(AbstractCloudConnector.java:61) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.AbstractCloudConnector.getServiceInfos(AbstractCloudConnector.java:40) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getServiceInfos(Cloud.java:89) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
   2017-06-27T17:58:26.74+0800 [APP/1] OUT 	at org.cloudfoundry.reconfiguration.spring.CloudPropertySourceApplicationContextInitializer.initialize(CloudPropertySourceApplicationContextInitializer.java:67) ~[spring_auto_reconfiguration-1.10.0_RELEASE.jar!/:na]
```

**Comment by nebhale** [comment]
This error comes out of [Spring Cloud Connectors](http://cloud.spring.io/spring-cloud-connectors/) and indicates that it doesn't know how to parse the credential payload that you've passed it.  I encourage you to ask questions in the locations that project suggests.
