### ISSUE TITLE
Getting syntax error with spring_boot_utils.rb

### ISSUE THREAD

**Issue by id027** [cloudfoundry/java-buildpack#545]
Hi all,

Suddenly I started to see this when building and deploying an app:

```
-----> Downloaded app package (61M)
-----> Downloaded app buildpack cache (314M)
Cloning into '/tmp/buildpacks/java-buildpack'...
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': /tmp/buildpacks/java-buildpack/lib/java_buildpack/util/spring_boot_utils.rb:48: syntax error, unexpected '.' (SyntaxError)
        return candidate if candidate&.exist?
                                       ^
/tmp/buildpacks/java-buildpack/lib/java_buildpack/util/spring_boot_utils.rb:51: syntax error, unexpected '.'
        return candidate if candidate&.exist?
        return candidate if candidate&.exist?
                                       ^
/tmp/buildpacks/java-buildpack/lib/java_buildpack/util/spring_boot_utils.rb:57: syntax error, unexpected '.'
        return candidate if candidate&.exist?
                                       ^
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/framework/container_customizer.rb:20:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:178:in `block in instantiate'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:175:in `map'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:175:in `instantiate'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:148:in `instantiate_components'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:141:in `initialize'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:264:in `new'
	from /tmp/buildpacks/java-buildpack/lib/java_buildpack/buildpack.rb:264:in `with_buildpack'
	from /tmp/buildpacks/java-buildpack/bin/compile:27:in `<main>'
Staging failed: Buildpack compilation step failed

FAILED
Error restarting application: BuildpackCompileFailed
```

Any hint, please?

**Comment by id027** [comment]
Ok, looks like I got it. The nil safe syntax is not supported with Ruby older than 2.3, right?

**Comment by nebhale** [comment]
@id027 Yeah, I believe so.  I recently updated to using it as part of dropping 2.2 compatibility (last supported version of CF aged out of Ruby 2.2).
