### ISSUE TITLE
"No suitable database driver found" exception after upgrading to Java Buildpack v4.8

### ISSUE THREAD

**Issue by janvnunen** [cloudfoundry/java-buildpack#574]
We upgraded our Java buildpack to v4.8 and now our Spring boot applications fail to start with the following error: "No suitable database driver found for consultation-portal-db service"

The stack trace looks like:

<pre>
2018-04-05T09:08:55.15+0200 [APP/PROC/WEB/0] OUT           "message": "[           main] o.s.boot.SpringApplication               : Application startup failed
org.cloudfoundry.reconfiguration.org.springframework.cloud.service.ServiceConnectorCreationException: Failed to created cloud datasource for consultation-portal-db service
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.relational.DataSourceCreator.create(DataSourceCreator.java:66)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.relational.DataSourceCreator.create(DataSourceCreator.java:26)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getServiceConnector(Cloud.java:292)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getSingletonServiceConnector(Cloud.java:202)
    at org.cloudfoundry.reconfiguration.CloudServiceUtils.getSingleCloudService(CloudServiceUtils.java:58)
    at org.cloudfoundry.reconfiguration.CloudServiceUtils.replaceBeanOfType(CloudServiceUtils.java:50)
    at org.cloudfoundry.reconfiguration.CloudServiceReconfigurationBeanFactoryPostProcessor.lambda$postProcessBeanFactory$1(CloudServiceReconfigurationBeanFactoryPostProcessor.java:59)
    at org.cloudfoundry.reconfiguration.ApplicationContextCloudServicesHolder.withCloudServices(ApplicationContextCloudServicesHolder.java:48)
    at org.cloudfoundry.reconfiguration.CloudServiceReconfigurationBeanFactoryPostProcessor.postProcessBeanFactory(CloudServiceReconfigurationBeanFactoryPostProcessor.java:52)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:131)
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523)
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
    at com.philips.dps.ConsultationPortalApplication.main(ConsultationPortalApplication.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
Caused by: org.cloudfoundry.reconfiguration.org.springframework.cloud.CloudException: No suitable database driver found for consultation-portal-db service 
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.relational.DataSourceCreator.getDriverClassName(DataSourceCreator.java:118)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.relational.DataSourceCreator.createPooledDataSource(DataSourceCreator.java:74)
    at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.relational.DataSourceCreator.create(DataSourceCreator.java:57)
    ... 27 common frames omitted
</pre>

The issue seems to be caused by the upgrade of Spring Auto-reconfiguration from `v1.12.0_RELEASE` to `v2.4.0_RELEASE` and can be solved by setting the environment variable `JBP_CONFIG_SPRING_AUTO_RECONFIGURATION` to `{ version : "1.12.0_RELEASE" }`.

Our datasource is defined in the `application.yml`:

<pre>
spring:
  profiles: cloud
  datasource:
    url: ${cloud.services.consultation-portal-db.connection.jdbcurl:jdbc:postgresql:consultation-portal-db}
    username: ${cloud.services.consultation-portal-db.connection.username:username}
    password: ${cloud.services.consultation-portal-db.connection.password:password}
    platform: postgres
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
</pre>

Our project is following the Spring Boot dependencies:

<pre>
com.philips.dps.pics:backend:jar:1.2.0-SNAPSHOT
+- org.springframework.boot:spring-boot-starter-data-jpa:jar:1.4.1.RELEASE:compile
|  +- org.springframework.boot:spring-boot-starter:jar:1.4.1.RELEASE:compile
|  |  +- org.springframework.boot:spring-boot:jar:1.4.1.RELEASE:compile
|  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.4.1.RELEASE:compile
|  |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.4.1.RELEASE:compile
|  |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.21:compile
|  |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.21:compile
|  |  \- org.yaml:snakeyaml:jar:1.17:runtime
|  +- org.springframework.boot:spring-boot-starter-aop:jar:1.4.1.RELEASE:compile
|  |  +- org.springframework:spring-aop:jar:4.3.3.RELEASE:compile
|  |  \- org.aspectj:aspectjweaver:jar:1.8.9:compile
+- org.postgresql:postgresql:jar:9.4.1211.jre7:compile
</pre>

When we start the application, we see the following output:

<pre>
Downloading build artifacts cache...
Creating container
Downloading app package...
Successfully created container
Downloaded build artifacts cache (94.6M)
Downloaded app package (98.3M)
-----> Java Buildpack v4.8 | https://github.com/cloudfoundry/java-buildpack.git#9f97630
-----> Downloading Jvmkill Agent 1.12.0_RELEASE from https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/jvmkill-1.12.0_RELEASE.so (found in cache)
-----> Downloading Open Jdk JRE 1.8.0_162 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_162.tar.gz (found in cache)
        Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.5s)
-----> Downloading Open JDK Like Memory Calculator 3.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-3.10.0_RELEASE.tar.gz (found in cache)
       Loaded Classes: 30196, Threads: 250
-----> Downloading Container Security Provider 1.13.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-security-provider/container-security-provider-1.13.0_RELEASE.jar (found in cache)

-----> Downloading Client Certificate Mapper 1.6.0_RELEASE from https://java-buildpack.cloudfoundry.org/client-certificate-mapper/client-certificate-mapper-1.6.0_RELEASE.jar (found in cache)
-----> Downloading Spring Auto Reconfiguration 2.4.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-2.4.0_RELEASE.jar (found in cache)
Uploading droplet...
Uploading build artifacts cache...
Exit status 0
Uploading droplet, build artifacts cache...
Uploaded build artifacts cache (94.6M)
Creating droplet for app with guid cf597b31-7171-4a90-8848-a02e260414e3
Uploaded droplet (144.4M)
Uploading complete
Stopping instance bdd1ba48-b053-418b-be52-655ead13e6e2
Creating container
Successfully created container
Destroying container
Successfully destroyed container
Starting health monitoring of container
JVM Memory Configuration: -Xss1M -Xmx1292M -XX:MaxDirectMemorySize=10M -XX:ReservedCodeCacheSize=240M
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
2018-04-05 10:33:19.356 DEBUG 12 --- [           main] c.p.dps.ConsultationPortalApplication    : Running with Spring Boot v1.4.1.RELEASE, Spring v4.3.3.RELEASE
 :: Spring Boot ::        (v1.4.1.RELEASE)
2018-04-05 10:33:19.282  INFO 12 --- [           main] nfigurationApplicationContextInitializer : Reconfiguration enabled
2018-04-05 10:33:19.357  INFO 12 --- [           main] c.p.dps.ConsultationPortalApplication    : The following profiles are active: cloud
 =========|_|==============|___/=/_/_/_/
2018-04-05 10:33:19.277  INFO 12 --- [           main] pertySourceApplicationContextInitializer : 'cloud' property source added
2018-04-05 10:33:19.355  INFO 12 --- [           main] c.p.dps.ConsultationPortalApplication    : Starting ConsultationPortalApplication on 1d27f7b6-f073-427a-59ed-5e21 with PID 12 (/home/vcap/app/BOOT-INF/classes started by vcap in /home/vcap/app)
2018-04-05 10:33:20.120  INFO 12 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@880ec60: startup date [Thu Apr 05 10:33:20 UTC 2018]; root of context hierarchy
       at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.relational.DataSourceCreator.create(DataSourceCreator.java:66)
       at org.cloudfoundry.reconfiguration.CloudServiceUtils.replaceBeanOfType(CloudServiceUtils.java:50)
       at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getServiceConnector(Cloud.java:292)
2018-04-05 10:33:24.592 ERROR 12 --- [           main] o.s.boot.SpringApplication               : Application startup failed
       at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
       at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:284)
       at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
       at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
       ... 27 common frames omitted
       at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:416)
2018-04-05 10:33:25.105  INFO 12 --- [ertificates.crt] org.cloudfoundry.security.FileWatcher    : Start watching /etc/ssl/certs/ca-certificates.crt
2018-04-05 10:33:25.333  INFO 12 --- [pool-1-thread-1] c.s.FileWatchingX509ExtendedTrustManager : Initialized TrustManager for /etc/ssl/certs/ca-certificates.crt
org.cloudfoundry.reconfiguration.org.springframework.cloud.service.ServiceConnectorCreationException: Failed to created cloud datasource for consultation-portal-db service
       at org.cloudfoundry.reconfiguration.org.springframework.cloud.service.relational.DataSourceCreator.create(DataSourceCreator.java:26)
       at org.cloudfoundry.reconfiguration.org.springframework.cloud.Cloud.getSingletonServiceConnector(Cloud.java:202)
       at org.cloudfoundry.reconfiguration.CloudServiceReconfigurationBeanFactoryPostProcessor.postProcessBeanFactory(CloudServiceReconfigurationBeanFactoryPostProcessor.java:52)
       at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:131)
       at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681)
       at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2018-04-05 10:33:24.612  WARN 12 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception thrown from LifecycleProcessor on context close
       at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:997)
       at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:818)
       at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
       at com.philips.dps.ConsultationPortalApplication.main(ConsultationPortalApplication.java:75)
</pre>

**Comment by janvnunen** [comment]
This problem is not caused by the Java build pack, but by invalid tags on our HSDP RDS PostgreSQL service. Independently on scheme and plan configured for the RDS service broker, it exposes the following list of tags:

<pre>
"tags": [
     "AWS",
    "RDS",
     "PostgreSQL",
     "MySQL",
     "Oracle"
    ],
</pre>

Since version 2.0 of the Spring Cloud Connectors project (https://github.com/spring-cloud/spring-cloud-connectors), the Spring Auto reconfiguration scans the tags and tries to load the corresponding database drivers. This fails because the MySQL driver is not available on the classpath, since we only use PostgreSQL. The problem can be fixed by removing all the faulty tags, so in our case it should only contain 'PostgreSQL' since we use the ‘postgres-medium-ha-dev’ plan.

As a workaround you can use a custom service data post-processor:

```java
package com.philips.dps.util;

import org.springframework.cloud.cloudfoundry.CloudFoundryRawServiceData;
import org.springframework.cloud.cloudfoundry.ServiceDataPostProcessor;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class HsdpRdsServiceDataPostProcessor implements ServiceDataPostProcessor {
  @SuppressWarnings("unchecked")
  @Override
  public CloudFoundryRawServiceData process(CloudFoundryRawServiceData serviceData) {
    final List<Map<String, Object>> hsdpRdsDataList = serviceData.get("hsdp-rds");

    if (hsdpRdsDataList != null) {
      for (Map<String, Object> hsdpRdsData : hsdpRdsDataList) {
        final String plan = (String) hsdpRdsData.get("plan");

        if (plan != null && plan.toLowerCase().contains("postgres")) {
          hsdpRdsData.put("tags", Collections.singletonList("PostgreSQL"));
        }
      }
    }
    return serviceData;
  }
}
```

To enable this custom service data provider, you have to create the file `META-INF/services/org.springframework.cloud.cloudfoundry.ServiceDataPostProcessor` with the following content:

```
com.philips.dps.util.HsdpRdsServiceDataPostProcessor
```
