### ISSUE TITLE
Cloud Foundry custom PKI certificates are not available when using Java 9, 10 or 11

### ISSUE THREAD

**Issue by mayrstefan** [cloudfoundry/java-buildpack#585]
Since some time the Java buildpack uses the container security provider to make os level PKI certificates available in Java. So we can add custom root certificates to our cloud foundry setup and use them for validation in all buildpacks.
This does not work in Java 9 or 10. I'm not sure if this is a buildpack issue or if this an issue of the container security provider itself.

We tested this using the Pivotal offline buildpack with an external source for Oracle Java:
```
cf set-env appname JBP_CONFIG_ORACLE_JRE "{ jre: {  repository_root: \"http://internalrepo.example.com\", version: \"10.0.1\" }  }
```

Then we use a small app where we iterate over the certificates and filter for our own certs:

```
TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
trustManagerFactory.init((KeyStore)null);
for (TrustManager trustManager : trustManagerFactory.getTrustManagers()) {
	if (trustManager instanceof X509TrustManager) {
		X509TrustManager x509TrustManager = (X509TrustManager)trustManager;
		for (X509Certificate cert : x509TrustManager.getAcceptedIssuers()) {
			if( cert.getSubjectDN().toString().matches(".*ACME.*")) {
			...
```

This works up to Java 1.8.0_172 but does not for 9.0.4 or 10.0.1.

**Comment by mayrstefan** [comment]
Any updates what's the cause for this changed behaviour?

**Comment by mayrstefan** [comment]
This issue still exists with Oracle JDK 11 and OpenJDK 11

**Comment by gwimmel** [comment]
I'm a colleague of Stefan and did some further analysis. Minimum example is the above code embedded into a simple JSP page. Buildpack-Version is 4.15, Tomcat 8.5.32, Oracle JDK 11.0.0_28. With JAVA_OPTS=-Djava.security.debug=all I can see the following exception in the log.

Seems to be a class loading problem?

` 
2018-09-28T13:47:11.85+0200 [APP/PROC/WEB/0] ERR java.lang.ClassNotFoundException: org.cloudfoundry.security.CloudFoundryContainerProvider
   2018-09-28T13:47:11.85+0200 [APP/PROC/WEB/0] ERR     at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
   2018-09-28T13:47:11.85+0200 [APP/PROC/WEB/0] ERR     at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
   2018-09-28T13:47:11.85+0200 [APP/PROC/WEB/0] ERR     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
   2018-09-28T13:47:11.85+0200 [APP/PROC/WEB/0] ERR     at java.base/sun.security.jca.ProviderConfig$ProviderLoader.legacyLoad(ProviderConfig.java:381)
   2018-09-28T13:47:11.85+0200 [APP/PROC/WEB/0] ERR     at java.base/sun.security.jca.ProviderConfig$ProviderLoader.load(ProviderConfig.java:358)
   2018-09-28T13:47:11.85+0200 [APP/PROC/WEB/0] ERR     at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:244)
   2018-09-28T13:47:11.85+0200 [APP/PROC/WEB/0] ERR     at java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:238)
   2018-09-28T13:47:11.85+0200 [APP/PROC/WEB/0] ERR     at java.base/java.security.AccessController.doPrivileged(Native Method)
   2018-09-28T13:47:11.86+0200 [APP/PROC/WEB/0] ERR     at java.base/sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:238)
   2018-09-28T13:47:11.86+0200 [APP/PROC/WEB/0] ERR     at java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:218)
   2018-09-28T13:47:11.86+0200 [APP/PROC/WEB/0] ERR     at java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:266)
   2018-09-28T13:47:11.86+0200 [APP/PROC/WEB/0] ERR     at java.base/sun.security.jca.ProviderList.getService(ProviderList.java:379)
   2018-09-28T13:47:11.86+0200 [APP/PROC/WEB/0] ERR     at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:157)
   2018-09-28T13:47:11.86+0200 [APP/PROC/WEB/0] ERR     at java.base/javax.net.ssl.TrustManagerFactory.getInstance(TrustManagerFactory.java:162)
   2018-09-28T13:47:11.86+0200 [APP/PROC/WEB/0] ERR     at org.apache.jsp.ssltest_jsp._jspService(ssltest_jsp.java:185)
`

A workaround seems to be to insert the Container Provider via code (in the minimum example e.g. just before the code that outputs the certificates):

`
Class<?> clazz = Class.forName("org.cloudfoundry.security.CloudFoundryContainerProvider");
Object provider = clazz.newInstance();
Security.insertProviderAt((Provider)provider, 2);
`

**Comment by mayrstefan** [comment]
After Guidos hint I started to hack a copy of the buildpack.

To get a Spring Boot application working I modifed java_main.rb and hacked the security provider directly into the classpath
```
       # old: classpath = @spring_boot_utils.is?(@application) ? '-cp $PWD/.' : @droplet.additional_libraries.as_classpath
       if @spring_boot_utils.is?(@application)
          classpath =  '-cp $PWD/.'
          if @droplet.java_home.java_9_or_later?
            classpath += ':$PWD/.java-buildpack/container_security_provider/container_security_provider-1.14.0_RELEASE.jar'
          end
        else
          classpath = @droplet.additional_libraries.as_classpath
        end
```
Then I verified the result with [willitconnect](https://github.com/krujos/willitconnect) - now the app could connect to a https website with a custom PKI certificate that was added to cloud foundry.

So starting with Java 9 there are libraries that have to be directly in the classpath. Linking them in /BOOT-INF/lib for Spring Boot or /WEB-INF/lib for Tomcat apps is not working anymore.

**Comment by mayrstefan** [comment]
So for verifying this with a Tomcat app my hack is even worse.
I extended write_set_env in tomcat_logging_support.rb:
```
CLASSPATH=$CLASSPATH:$PWD/.java-buildpack/container_security_provider/container_security_provider-1.14.0_RELEASE.jar
```

With this hack the demo code from my initial issue description is working again.

I guess not only Spring Boot and Tomcats apps are affected by this class loading change in Java 9+. Other implemented container types of the Java Buildpack might run into the same issue.

**Comment by shchoube** [comment]
same issue. any release date for 4.17?
