### ISSUE TITLE
error when building offline buildpack v4.9 due to introscope_agent.yml

### ISSUE THREAD

**Issue by torstenwalter** [cloudfoundry/java-buildpack#590]
## Steps to reproduce:

```
git clone https://github.com/cloudfoundry/java-buildpack.git
cd java-buildpack/
git checkout v4.9
docker run -it --rm -v "$PWD:/usr/src" -w /usr/src ruby:2.5 bash -c "bundle install && bundle exec rake clean package OFFLINE=true"
```

This is the error message shown:

```
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Fetching webmock 3.2.1
Installing webmock 3.2.1
Fetching yard 0.9.12
Installing yard 0.9.12
Bundle complete! 10 Gemfile dependencies, 28 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
Post-install message from yard:
--------------------------------------------------------------------------------
As of YARD v0.9.2:

RubyGems "--document=yri,yard" hooks are now supported. You can auto-configure
YARD to automatically build the yri index for installed gems by typing:

    $ yard config --gem-install-yri

See `yard config --help` for more information on RubyGems install hooks.

You can also add the following to your .gemspec to have YARD document your gem
on install:

    spec.metadata["yard.run"] = "yri" # use "yard" to build full HTML docs.

--------------------------------------------------------------------------------
rake aborted!
Unable to resolve version '10.6.0_0' for platform ''
/usr/src/rakelib/dependency_cache_task.rb:174:in `block in get_from_cache'
/usr/src/lib/java_buildpack/util/cache/cached_file.rb:57:in `block in cached'
/usr/src/lib/java_buildpack/util/cache/cached_file.rb:57:in `open'
/usr/src/lib/java_buildpack/util/cache/cached_file.rb:57:in `open'
/usr/src/lib/java_buildpack/util/cache/cached_file.rb:57:in `cached'
/usr/src/lib/java_buildpack/util/cache/download_cache.rb:80:in `get'
/usr/src/rakelib/dependency_cache_task.rb:168:in `get_from_cache'
/usr/src/rakelib/dependency_cache_task.rb:160:in `block (2 levels) in uris'
/usr/src/rakelib/dependency_cache_task.rb:158:in `each'
/usr/src/rakelib/dependency_cache_task.rb:158:in `block in uris'
/usr/src/rakelib/dependency_cache_task.rb:157:in `each'
/usr/src/rakelib/dependency_cache_task.rb:157:in `uris'
/usr/src/rakelib/dependency_cache_task.rb:46:in `initialize'
/usr/src/rakefile:42:in `new'
/usr/src/rakefile:42:in `<top (required)>'
/usr/local/bundle/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

## Workaround:
`rm config/introscope_agent.yml`

If you then run the build again it succeeds.
```
docker run -it --rm -v "$PWD:/usr/src" -w /usr/src ruby:2.5 bash -c "bundle install && bundle exec rake clean package OFFLINE=true"
```

Now the output ends with:

```
chmod 644 build/staging/resources/luna_security_provider/Chrystoki.conf
chmod 644 build/staging/LICENSE
Creating build/java-buildpack-offline-v4.9.zip
```

**Comment by nebhale** [comment]
Yep, as expected CA has removed a version from their repository.  If you look [here](https://ca.bintray.com/apm-agents/index.yml), you'll see that the version we released against isn't in that list for download anymore.  Even AppDynamics [removed a version](https://packages.appdynamics.com/java/index.yml) from a release we did two weeks ago.

**Comment by nebhale** [comment]
@DMevada It appears that some of the versions of the Introscope agent have been removed from your repository.  Specifically, `10.6.0_0` (released in 4.9) and `10.7.0_70` (released in 4.10) are both missing.  Could you please add both of those versions back, update the `index.yml` and invalidate any caches that might influence the visibility of those changes.

**Comment by DMevada** [comment]
Hi @nebhale 

It is not feasible to maintain all earlier versions given that our releases are every few weeks.
Do you have any best practices so that we can only maintain the latest version of every major release?

@torstenwalter 
If you need introscope, you can use version 4.11 of the buildpack.

**Comment by nebhale** [comment]
It not only is feasible (just take a look at what [AppDynamics](https://packages.appdynamics.com/java/index.yml) is doing or what we're doing for [New Relic](https://download.run.pivotal.io/new-relic/index.yml)) but is an **absolute requirement** for being included in the Java Buildpack.  Much like a Maven or Debian repository, once an artifact has been added to a public repository, it **can never be removed**.  Removing artifacts that other projects actively depend on effectively makes it so that stable systems can never be reproduced.

If you cannot maintain all released artifacts and an `index.yml` that points to them, then we'll need to disable the Introscope integration until you can.

**Comment by DMevada** [comment]
I will upload the missing artifacts and let you know once it's complete.

**Comment by DMevada** [comment]
I have uploaded the missing artifacts as well as an updated index.yml.

**Comment by nebhale** [comment]
@torstenwalter Can you please have another crack at building?

**Comment by torstenwalter** [comment]
It works now as expected for v4.9. 

I retested for v4.11 `Unable to resolve version '4.4.1_21006' for platform ''` In that version it's `./config/app_dynamics_agent.yml` which is not present.

What would be the expected behaviour? Should users be able to rely on the fact that they are able to rebuild different versions of the java buildback or is it necessary to replicate the repository as described in https://github.com/cloudfoundry/java-buildpack/blob/master/docs/buildpack-modes.md#replicating-the-repository-optional?

It feels a little strange that there is a documentation for expert mode and how the repository can be replicated, but it's not done consistently for the buildpack itself. Would it be an option that you replicate all dependencies used during buildtimes on your servers so that the buildpack could always be rebuild using those?

**Comment by nebhale** [comment]
This is AppDynamics removing things from their repository as well which I have to chase down.  The replication of the repository isn’t strictly in order to ensure that things aren’t being removed, it’s primarily for situations where staging doesn’t have access to the internet.  At issue is that as an Open Source project, concerned with export compliance controls, Cloud Foundry cannot host many of these extensions themselves.  We are at the mercy of partners behaving well with regards to repositories periodically have to remind them of what reproducible builds mean.

**Comment by nebhale** [comment]
@torstenwalter After much wrangling of partners, I've confirmed that all of the releases in the 4.x line (at least) can be built again.  Let me know if you have any problems building from your location.

**Comment by torstenwalter** [comment]
v.4.9, v4.10 and v4.12 work as expected, but for  v4.11 I'm still getting an error:

```
Unable to resolve version '4.4.1_21006' for platform ''
/usr/src/rakelib/dependency_cache_task.rb:174:in `block in get_from_cache'
```

`grep -R 4.4.1_21006 .` results in `./config/app_dynamics_agent.yml:version: 4.4.1_21006`

**Comment by nebhale** [comment]
Hmm...  That was the one I was working on fixing directly with AppDynamics and tested repeatedly yesterday.  Let me look at it again.

**Comment by nebhale** [comment]
Just verified it from my home computer but it might still be using the same CloudFront edge server (AppDynamics uses CloudFront for their CDN) as the office.  The instructions don't include this (I don't think) but you can you give you build a run with `clean` or `clobber` (_really_ clean) to ensure that you don't have something cached?

```
$ bundle exec rake clobber package OFFLINE=true
```

**Comment by torstenwalter** [comment]
Tested again with 
`$ bundle exec rake clobber package OFFLINE=true`
Same result as before. How does the final URL for the artefact look like? Then I could test that with curl just to see what happens.

**Comment by nebhale** [comment]
@torstenwalter The command is 

```
$ curl -sSL https://packages.appdynamics.com/java/index.yml -H "user-agent: Ruby" -H "accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3" -H "accept: */*"
```

Notably, the headers actually matter as CloudFront's caching takes them into account.  I'll head back to AppDynamics and figure out what's going on.

**Comment by torstenwalter** [comment]
That's the output:

```
---
4.1.3_1: https://packages.appdynamics.com/java/4.1.3.1/AppServerAgent-4.1.3.1.zip
4.1.7_1: https://packages.appdynamics.com/java/4.1.7.1/AppServerAgent-4.1.7.1.zip
4.1.7_2: https://packages.appdynamics.com/java/4.1.7.2/AppServerAgent-4.1.7.2.zip
4.1.8_1: https://packages.appdynamics.com/java/4.1.8.1/AppServerAgent-4.1.8.1.zip
4.1.8_2: https://packages.appdynamics.com/java/4.1.8.2/AppServerAgent-4.1.8.2.zip
4.1.8_3: https://packages.appdynamics.com/java/4.1.8.3/AppServerAgent-4.1.8.3.zip
4.1.8_4: https://packages.appdynamics.com/java/4.1.8.4/AppServerAgent-4.1.8.4.zip
4.1.8_5: https://packages.appdynamics.com/java/4.1.8.5/AppServerAgent-4.1.8.5.zip
4.1.8_6: https://packages.appdynamics.com/java/4.1.8.6/AppServerAgent-4.1.8.6.zip
4.1.8_7: https://packages.appdynamics.com/java/4.1.8.7/AppServerAgent-4.1.8.7.zip
4.1.8_8: https://packages.appdynamics.com/java/4.1.8.8/AppServerAgent-4.1.8.8.zip
4.1.8_9: https://packages.appdynamics.com/java/4.1.8.9/AppServerAgent-4.1.8.9.zip
4.1.8_10: https://packages.appdynamics.com/java/4.1.8.10/AppServerAgent-4.1.8.10.zip
4.1.8_11: https://packages.appdynamics.com/java/4.1.8.11/AppServerAgent-4.1.8.11.zip
4.1.8_12: https://packages.appdynamics.com/java/4.1.8.12/AppServerAgent-4.1.8.12.zip
4.1.8_13: https://packages.appdynamics.com/java/4.1.8.13/AppServerAgent-4.1.8.13.zip
4.1.10_1: https://packages.appdynamics.com/java/4.1.10.1/AppServerAgent-4.1.10.1.zip
4.1.10_2: https://packages.appdynamics.com/java/4.1.10.2/AppServerAgent-4.1.10.2.zip
4.1.10_3: https://packages.appdynamics.com/java/4.1.10.3/AppServerAgent-4.1.10.3.zip
4.1.10_4: https://packages.appdynamics.com/java/4.1.10.4/AppServerAgent-4.1.10.4.zip
4.1.10_6: https://packages.appdynamics.com/java/4.1.10.6/AppServerAgent-4.1.10.6.zip
4.2.0_1: https://packages.appdynamics.com/java/4.2.0.1/AppServerAgent-4.2.0.1.zip
4.2.0_2: https://packages.appdynamics.com/java/4.2.0.2/AppServerAgent-4.2.0.2.zip
4.2.1_1: https://packages.appdynamics.com/java/4.2.1.1/AppServerAgent-4.2.1.1.zip
4.2.1_2: https://packages.appdynamics.com/java/4.2.1.2/AppServerAgent-4.2.1.2.zip
4.2.1_3: https://packages.appdynamics.com/java/4.2.1.3/AppServerAgent-4.2.1.3.zip
4.2.1_4: https://packages.appdynamics.com/java/4.2.1.4/AppServerAgent-4.2.1.4.zip
4.2.1_5: https://packages.appdynamics.com/java/4.2.1.5/AppServerAgent-4.2.1.5.zip
4.2.1_6: https://packages.appdynamics.com/java/4.2.1.6/AppServerAgent-4.2.1.6.zip
4.2.1_7: https://packages.appdynamics.com/java/4.2.1.7/AppServerAgent-4.2.1.7.zip
4.2.1_8: https://packages.appdynamics.com/java/4.2.1.8/AppServerAgent-4.2.1.8.zip
4.2.2_1: https://packages.appdynamics.com/java/4.2.2.1/AppServerAgent-4.2.2.1.zip
4.2.2_2: https://packages.appdynamics.com/java/4.2.2.2/AppServerAgent-4.2.2.2.zip
4.2.3_1: https://packages.appdynamics.com/java/4.2.3.1/AppServerAgent-4.2.3.1.zip
4.2.3_2: https://packages.appdynamics.com/java/4.2.3.2/AppServerAgent-4.2.3.2.zip
4.2.3_3: https://packages.appdynamics.com/java/4.2.3.3/AppServerAgent-4.2.3.3.zip
4.2.4_1: https://packages.appdynamics.com/java/4.2.4.1/AppServerAgent-4.2.4.1.zip
4.2.12_2: https://packages.appdynamics.com/java/4.2.12.2/AppServerAgent-4.2.12.2.zip
4.2.15_1: https://packages.appdynamics.com/java/4.2.15.1/AppServerAgent-4.2.15.1.zip
4.2.15_2: https://packages.appdynamics.com/java/4.2.15.2/AppServerAgent-4.2.15.2.zip
4.2.15_3: https://packages.appdynamics.com/java/4.2.15.3/AppServerAgent-4.2.15.3.zip
4.2.15_4: https://packages.appdynamics.com/java/4.2.15.4/AppServerAgent-4.2.15.4.zip
4.2.15_5: https://packages.appdynamics.com/java/4.2.15.5/AppServerAgent-4.2.15.5.zip
4.2.15_6: https://packages.appdynamics.com/java/4.2.15.6/AppServerAgent-4.2.15.6.zip
4.2.15_7: https://packages.appdynamics.com/java/4.2.15.7/AppServerAgent-4.2.15.7.zip
4.2.15_8: https://packages.appdynamics.com/java/4.2.15.8/AppServerAgent-4.2.15.8.zip
4.2.15_9: https://packages.appdynamics.com/java/4.2.15.9/AppServerAgent-4.2.15.9.zip
4.2.15_10: https://packages.appdynamics.com/java/4.2.15.10/AppServerAgent-4.2.15.10.zip
4.2.15_11: https://packages.appdynamics.com/java/4.2.15.11/AppServerAgent-4.2.15.11.zip
4.2.15_12: https://packages.appdynamics.com/java/4.2.15.12/AppServerAgent-4.2.15.12.zip
4.2.15_13: https://packages.appdynamics.com/java/4.2.15.13/AppServerAgent-4.2.15.13.zip
4.2.15_14: https://packages.appdynamics.com/java/4.2.15.14/AppServerAgent-4.2.15.14.zip
4.2.15_15: https://packages.appdynamics.com/java/4.2.15.15/AppServerAgent-4.2.15.15.zip
4.2.15_16: https://packages.appdynamics.com/java/4.2.15.16/AppServerAgent-4.2.15.16.zip
4.2.15_17: https://packages.appdynamics.com/java/4.2.15.17/AppServerAgent-4.2.15.17.zip
4.2.15_18: https://packages.appdynamics.com/java/4.2.15.18/AppServerAgent-4.2.15.18.zip
4.2.15_19: https://packages.appdynamics.com/java/4.2.15.19/AppServerAgent-4.2.15.19.zip
4.3.0_1: https://packages.appdynamics.com/java/4.3.0.1/AppServerAgent-4.3.0.1.zip
4.3.0_2: https://packages.appdynamics.com/java/4.3.0.2/AppServerAgent-4.3.0.2.zip
4.3.0_3: https://packages.appdynamics.com/java/4.3.0.3/AppServerAgent-4.3.0.3.zip
4.3.0_4: https://packages.appdynamics.com/java/4.3.0.4/AppServerAgent-4.3.0.4.zip
4.3.0_5: https://packages.appdynamics.com/java/4.3.0.5/AppServerAgent-4.3.0.5.zip
4.3.0_6: https://packages.appdynamics.com/java/4.3.0.6/AppServerAgent-4.3.0.6.zip
4.3.1_1: https://packages.appdynamics.com/java/4.3.1.1/AppServerAgent-4.3.1.1.zip
4.3.1_2: https://packages.appdynamics.com/java/4.3.1.2/AppServerAgent-4.3.1.2.zip
4.3.1_3: https://packages.appdynamics.com/java/4.3.1.3/AppServerAgent-4.3.1.3.zip
4.3.1_4: https://packages.appdynamics.com/java/4.3.1.4/AppServerAgent-4.3.1.4.zip
4.3.1_5: https://packages.appdynamics.com/java/4.3.1.5/AppServerAgent-4.3.1.5.zip
4.3.1_6: https://packages.appdynamics.com/java/4.3.1.6/AppServerAgent-4.3.1.6.zip
4.3.2_1: https://packages.appdynamics.com/java/4.3.2.1/AppServerAgent-4.3.2.1.zip
4.3.2_2: https://packages.appdynamics.com/java/4.3.2.2/AppServerAgent-4.3.2.2.zip
4.3.2_3: https://packages.appdynamics.com/java/4.3.2.3/AppServerAgent-4.3.2.3.zip
4.3.2_5: https://packages.appdynamics.com/java/4.3.2.5/AppServerAgent-4.3.2.5.zip
4.3.3_1: https://packages.appdynamics.com/java/4.3.3.1/AppServerAgent-4.3.3.1.zip
4.3.3_2: https://packages.appdynamics.com/java/4.3.3.2/AppServerAgent-4.3.3.2.zip
4.3.3_3: https://packages.appdynamics.com/java/4.3.3.3/AppServerAgent-4.3.3.3.zip
4.3.3_4: https://packages.appdynamics.com/java/4.3.3.4/AppServerAgent-4.3.3.4.zip
4.3.3_5: https://packages.appdynamics.com/java/4.3.3.5/AppServerAgent-4.3.3.5.zip
4.3.3_6: https://packages.appdynamics.com/java/4.3.3.6/AppServerAgent-4.3.3.6.zip
4.3.3_7: https://packages.appdynamics.com/java/4.3.3.7/AppServerAgent-4.3.3.7.zip
4.3.3_8: https://packages.appdynamics.com/java/4.3.3.8/AppServerAgent-4.3.3.8.zip
4.3.3_9: https://packages.appdynamics.com/java/4.3.3.9/AppServerAgent-4.3.3.9.zip
4.3.3_10: https://packages.appdynamics.com/java/4.3.3.10/AppServerAgent-4.3.3.10.zip
4.3.3_11: https://packages.appdynamics.com/java/4.3.3.11/AppServerAgent-4.3.3.11.zip
4.3.3_12: https://packages.appdynamics.com/java/4.3.3.12/AppServerAgent-4.3.3.12.zip
4.3.3_13: https://packages.appdynamics.com/java/4.3.3.13/AppServerAgent-4.3.3.13.zip
4.3.4_1: https://packages.appdynamics.com/java/4.3.4.1/AppServerAgent-4.3.4.1.zip
4.3.4_2: https://packages.appdynamics.com/java/4.3.4.2/AppServerAgent-4.3.4.2.zip
4.3.4_3: https://packages.appdynamics.com/java/4.3.4.3/AppServerAgent-4.3.4.3.zip
4.3.5_1: https://packages.appdynamics.com/java/4.3.5.1/AppServerAgent-4.3.5.1.zip
4.3.5_2: https://packages.appdynamics.com/java/4.3.5.2/AppServerAgent-4.3.5.2.zip
4.3.5_5: https://packages.appdynamics.com/java/4.3.5.5/AppServerAgent-4.3.5.5.zip
4.3.5_6: https://packages.appdynamics.com/java/4.3.5.6/AppServerAgent-4.3.5.6.zip
4.3.5_8: https://packages.appdynamics.com/java/4.3.5.8/AppServerAgent-4.3.5.8.zip
4.3.5_9: https://packages.appdynamics.com/java/4.3.5.9/AppServerAgent-4.3.5.9.zip
4.3.5_10: https://packages.appdynamics.com/java/4.3.5.10/AppServerAgent-4.3.5.10.zip
4.3.5_11: https://packages.appdynamics.com/java/4.3.5.11/AppServerAgent-4.3.5.11.zip
4.3.5_12: https://packages.appdynamics.com/java/4.3.5.12/AppServerAgent-4.3.5.12.zip
4.3.5_13: https://packages.appdynamics.com/java/4.3.5.13/AppServerAgent-4.3.5.13.zip
4.3.7_1: https://packages.appdynamics.com/java/4.3.7.1/AppServerAgent-4.3.7.1.zip
4.3.7_2: https://packages.appdynamics.com/java/4.3.7.2/AppServerAgent-4.3.7.2.zip
4.3.7_3: https://packages.appdynamics.com/java/4.3.7.3/AppServerAgent-4.3.7.3.zip
4.3.7_4: https://packages.appdynamics.com/java/4.3.7.4/AppServerAgent-4.3.7.4.zip
4.3.7_5: https://packages.appdynamics.com/java/4.3.7.5/AppServerAgent-4.3.7.5.zip
4.3.8_1: https://packages.appdynamics.com/java/4.3.8.1/AppServerAgent-4.3.8.1.zip
4.3.8_2: https://packages.appdynamics.com/java/4.3.8.2/AppServerAgent-4.3.8.2.zip
4.3.8_3: https://packages.appdynamics.com/java/4.3.8.3/AppServerAgent-4.3.8.3.zip
4.3.8_4: https://packages.appdynamics.com/java/4.3.8.4/AppServerAgent-4.3.8.4.zip
4.3.8_5: https://packages.appdynamics.com/java/4.3.8.5/AppServerAgent-4.3.8.5.zip
4.3.8_6: https://packages.appdynamics.com/java/4.3.8.6/AppServerAgent-4.3.8.6.zip
4.3.8_7: https://packages.appdynamics.com/java/4.3.8.7/AppServerAgent-4.3.8.7.zip
4.4.0_3: https://packages.appdynamics.com/java/4.4.0.3/AppServerAgent-4.4.0.3.zip
4.4.3_22593: https://packages.appdynamics.com/java/4.4.3.22593/AppServerAgent-4.4.3.22593.zip
4.4.3_23049: https://packages.appdynamics.com/java/4.4.3.23049/AppServerAgent-4.4.3.23049.zip
4.4.3_23079: https://packages.appdynamics.com/java/4.4.3.23079/AppServerAgent-4.4.3.23079.zip
```

Hope this helps.

**Comment by nebhale** [comment]
@torstenwalter Give that `curl` another go and if you see `4.4.1` in it, go ahead and try the build again.  AppDynamics thinks they've finally gotten to the bottom of their caching issues.

**Comment by torstenwalter** [comment]
Works like charm. A big thank you to everyone involved.
