### ISSUE TITLE
Cannot establish secure SSL connection in vanilla java app while truststore is enabled.

### ISSUE THREAD

**Issue by dam5s** [cloudfoundry/java-buildpack#651]
I need to connect to a remote MySQL database using SSL and while validating the certificate.

In a spring app, I can add the TrustStore to my Jar and set up the JVM options to load it correctly, it just works.
See minimal example at https://github.com/dam5s/rds-test-app-spring

In a jetty based app (no spring dependencies at all), doing the same thing does not work, unless I add this environment variable to my manifest:
```
 JBP_CONFIG_CONTAINER_SECURITY_PROVIDER: '{key_manager_enabled: false, trust_manager_enabled: false}'
```
See minimal example at https://github.com/dam5s/rds-test-app-jetty

Both of these samples work perfectly fine locally.

I would have expected for the buildpack to behave the same way for a Spring or a vanilla Java app in regards to trust store management.

**Comment by nebhale** [comment]
What does the failure look like?

**Comment by dam5s** [comment]
Cannot connect to the database. No packets received on socket connection.

**Comment by dam5s** [comment]
Here are the detailed exception logs for the one request to `/`

```
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR Communications link failure
   2018-11-16T10:52:42.24-0700 [RTR/7] OUT rds-test-app-jetty.cfapps.io - [2018-11-16T17:52:41.077+0000] "GET / HTTP/1.1" 404 0 315 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0" "10.10.66.142:58816" "10.10.148.218:61130" x_forwarded_for:"96.78.5.113, 10.10.66.142" x_forwarded_proto:"http" vcap_request_id:"fe64111b-9da8-410b-51c0-14fd9bf5b6de" response_time:1.163208021 app_id:"5976b216-f05f-41c7-9bae-b7fda90a518f" app_index:"0" x_b3_traceid:"5e2b2a76f846b05d" x_b3_spanid:"5e2b2a76f846b05d" x_b3_parentspanid:"-"
   2018-11-16T10:52:42.24-0700 [RTR/7] OUT 
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:590)
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:57)
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:423)
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:139)
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:110)
   2018-11-16T10:52:42.19-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:107)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at rdstestapp.HomeHandler.handle(App.kt:47)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.server.Server.handle(Server.java:530)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at java.base/java.lang.Thread.run(Unknown Source)
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR Caused by: com.mysql.cj.core.exceptions.CJCommunicationsException: Communications link failure
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
   2018-11-16T10:52:42.20-0700 [APP/PROC/WEB/0] ERR 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:93)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:133)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.core.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:149)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.io.MysqlaProtocol.negotiateSSLConnection(MysqlaProtocol.java:309)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.negotiateSSLConnection(MysqlaAuthenticationProvider.java:769)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(MysqlaAuthenticationProvider.java:482)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.connect(MysqlaAuthenticationProvider.java:204)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.io.MysqlaProtocol.connect(MysqlaProtocol.java:1414)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.MysqlaSession.connect(MysqlaSession.java:132)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1726)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1596)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	... 27 more
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR Caused by: java.net.SocketException: Broken pipe (Write failed)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/java.net.SocketOutputStream.socketWrite(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/java.net.SocketOutputStream.write(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeChangeCipherSpec(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.OutputRecord.changeWriteCiphers(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.changeWriteCiphers(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.Handshaker.sendChangeCipherSpec(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.ClientHandshaker.serverHelloDone(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.Handshaker.processLoop(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.Handshaker.processRecord(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   2018-11-16T10:52:42.21-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   2018-11-16T10:52:42.22-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.core.io.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:156)
   2018-11-16T10:52:42.22-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.io.MysqlaProtocol.negotiateSSLConnection(MysqlaProtocol.java:304)
   2018-11-16T10:52:42.22-0700 [APP/PROC/WEB/0] ERR 	... 34 more
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR Communications link failure
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:590)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:57)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:423)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:139)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.MysqlDataSource.getConnection(MysqlDataSource.java:110)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:107)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at rdstestapp.HomeHandler.handle(App.kt:47)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.server.Server.handle(Server.java:530)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at java.base/java.lang.Thread.run(Unknown Source)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR Caused by: com.mysql.cj.core.exceptions.CJCommunicationsException: Communications link failure
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
   2018-11-16T10:52:43.52-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:54)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:93)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.core.exceptions.ExceptionFactory.createException(ExceptionFactory.java:133)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.core.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:149)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.io.MysqlaProtocol.negotiateSSLConnection(MysqlaProtocol.java:309)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.negotiateSSLConnection(MysqlaAuthenticationProvider.java:769)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(MysqlaAuthenticationProvider.java:482)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.authentication.MysqlaAuthenticationProvider.connect(MysqlaAuthenticationProvider.java:204)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.io.MysqlaProtocol.connect(MysqlaProtocol.java:1414)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.MysqlaSession.connect(MysqlaSession.java:132)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:1726)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1596)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	... 27 more
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR Caused by: java.net.SocketException: Broken pipe (Write failed)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
   2018-11-16T10:52:43.54-0700 [RTR/5] OUT rds-test-app-jetty.cfapps.io - [2018-11-16T17:52:42.434+0000] "GET /favicon.ico HTTP/1.1" 404 0 326 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0" "10.10.66.142:28172" "10.10.148.218:61130" x_forwarded_for:"96.78.5.113, 10.10.66.142" x_forwarded_proto:"http" vcap_request_id:"36f11899-a71b-479c-4b16-8d6088f6137d" response_time:1.112588833 app_id:"5976b216-f05f-41c7-9bae-b7fda90a518f" app_index:"0" x_b3_traceid:"a0592b71183abc9d" x_b3_spanid:"a0592b71183abc9d" x_b3_parentspanid:"-"
   2018-11-16T10:52:43.54-0700 [RTR/5] OUT 
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/java.net.SocketOutputStream.socketWrite(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/java.net.SocketOutputStream.write(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeChangeCipherSpec(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.OutputRecord.changeWriteCiphers(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.changeWriteCiphers(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.Handshaker.sendChangeCipherSpec(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.ClientHandshaker.serverHelloDone(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.Handshaker.processLoop(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.Handshaker.processRecord(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.processInputRecord(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.core.io.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:156)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	at com.mysql.cj.mysqla.io.MysqlaProtocol.negotiateSSLConnection(MysqlaProtocol.java:304)
   2018-11-16T10:52:43.54-0700 [APP/PROC/WEB/0] ERR 	... 34 more
```

**Comment by nebhale** [comment]
Trust Store management is handled generically (a `SecurityProvider`, added to the JVM, and acting as the "default" `TrustStore`).  Where this might change is how either Tomcat or Jetty chooses to instantiate their `TrustStore`.  I'd also point out that there's no indication that there's an SSL trust issue in those logs; all we see is a broken pipe.  So without more diagnostics (we specifically don't work with the MySQL JDBC driver due to licensing restrictions) I'm not sure how much I can help you.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
