### ISSUE TITLE
CF Push fails with invalid Unzipping "CEN header (bad signature)" error

### ISSUE THREAD

**Issue by pink95** [cloudfoundry/java-buildpack#716]
I am trying to push my UI app to PCF using the command

`cf push applicaiton-name -p warfile.war`

The application compiles and runs fine on local. However the push fails with the following error:

```
Staging app and tracing logs...
   Downloading java_buildpack_offline_v4_9...
   Downloaded java_buildpack_offline_v4_9
   Cell 861b0728-9402-4d79-b396-0a93b9a4dd6c creating container for instance 8377e42e-1265-4f50-9c8b-94ac40b83efc
   Cell 861b0728-9402-4d79-b396-0a93b9a4dd6c successfully created container for instance 8377e42e-1265-4f50-9c8b-94ac40b83efc
   Downloading build artifacts cache...
   Downloading app package...
   Downloaded build artifacts cache (131B)
   Downloaded app package (35.4M)
   warning [/tmp/app/WEB-INF/lib/poi-ooxml-schemas-3.11.jar]:  652746 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   error [/tmp/app/WEB-INF/lib/poi-ooxml-schemas-3.11.jar]:  reported length of central directory is
     -652746 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
     zipfile?).  Compensating...
   -----> Java Buildpack v4.9 (offline) | https://github.com/cloudfoundry/java-buildpack.git#830f4c3
   -----> Downloading Jvmkill Agent 1.12.0_RELEASE from https://java-buildpack.cloudfoundry.org/jvmkill/trusty/x86_64/jvmkill-1.12.0_RELEASE.so (found in cache)
   -----> Downloading Open Jdk JRE 1.8.0_162 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_162.tar.gz (found in cache)
          Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.0s)
          JVM DNS caching disabled in lieu of BOSH DNS caching
   -----> Downloading Open JDK Like Memory Calculator 3.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-3.10.0_RELEASE.tar.gz (found in cache)
   warning [/tmp/app/WEB-INF/lib/poi-ooxml-schemas-3.11.jar]:  652746 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   error [/tmp/app/WEB-INF/lib/poi-ooxml-schemas-3.11.jar]:  reported length of central directory is
     -652746 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
     zipfile?).  Compensating...
          Loaded Classes: 18393, Threads: 250
   -----> Downloading Client Certificate Mapper 1.5.0_RELEASE from https://java-buildpack.cloudfoundry.org/client-certificate-mapper/client-certificate-mapper-1.5.0_RELEASE.jar (found in cache)
   -----> Downloading Container Customizer 2.6.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-customizer/container-customizer-2.6.0_RELEASE.jar (found in cache)
   -----> Downloading Container Security Provider 1.13.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-security-provider/container-security-provider-1.13.0_RELEASE.jar (found in cache)
   -----> Downloading Spring Auto Reconfiguration 2.3.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-2.3.0_RELEASE.jar (found in cache)
   warning [/tmp/app/WEB-INF/lib/poi-ooxml-schemas-3.11.jar]:  652746 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   error [/tmp/app/WEB-INF/lib/poi-ooxml-schemas-3.11.jar]:  reported length of central directory is
     -652746 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
     zipfile?).  Compensating...
   warning [/tmp/app/WEB-INF/lib/poi-ooxml-schemas-3.11.jar]:  652746 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   error [/tmp/app/WEB-INF/lib/poi-ooxml-schemas-3.11.jar]:  reported length of central directory is
     -652746 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
     zipfile?).  Compensating...
   Exit status 0
   Uploading droplet, build artifacts cache...
   Uploading build artifacts cache...
   Uploading droplet...
   Uploaded build artifacts cache (131B)
   Uploaded droplet (81.6M)
   Uploading complete
   Cell 861b0728-9402-4d79-b396-0a93b9a4dd6c stopping instance 8377e42e-1265-4f50-9c8b-94ac40b83efc
   Cell 861b0728-9402-4d79-b396-0a93b9a4dd6c destroying container for instance 8377e42e-1265-4f50-9c8b-94ac40b83efc
   Cell 861b0728-9402-4d79-b396-0a93b9a4dd6c successfully destroyed container for instance 8377e42e-1265-4f50-9c8b-94ac40b83efc

Waiting for app to start...
Start unsuccessful

TIP: use 'cf logs CTGArcPorC --recent' for more information
FAILED
```

The logs say:

```
2019-04-08T15:23:14.808+05:30 [APP/PROC/WEB/0] [ERR] Exception in thread "main" java.util.zip.ZipException: invalid CEN header (bad signature)
2019-04-08T15:23:14.808+05:30 [APP/PROC/WEB/0] [ERR] at java.util.zip.ZipFile.open(Native Method)
2019-04-08T15:23:14.808+05:30 [APP/PROC/WEB/0] [ERR] at java.util.zip.ZipFile.<init>(ZipFile.java:225)
2019-04-08T15:23:14.808+05:30 [APP/PROC/WEB/0] [ERR] at java.util.zip.ZipFile.<init>(ZipFile.java:155)
2019-04-08T15:23:14.809+05:30 [APP/PROC/WEB/0] [ERR] at java.util.jar.JarFile.<init>(JarFile.java:166)
2019-04-08T15:23:14.809+05:30 [APP/PROC/WEB/0] [ERR] at java.util.jar.JarFile.<init>(JarFile.java:130)
2019-04-08T15:23:14.809+05:30 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:112)
2019-04-08T15:23:14.809+05:30 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:106)
2019-04-08T15:23:14.809+05:30 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:92)
2019-04-08T15:23:14.809+05:30 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:83)
2019-04-08T15:23:14.809+05:30 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61)
2019-04-08T15:23:14.809+05:30 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57)
2019-04-08T15:23:14.809+05:30 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchive(ExplodedArchive.java:123)
2019-04-08T15:23:14.809+05:30 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchives(ExplodedArchive.java:110)
2019-04-08T15:23:14.810+05:30 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:72)
2019-04-08T15:23:14.810+05:30 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
2019-04-08T15:23:14.810+05:30 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
2019-04-08T15:23:14.833+05:30 [APP/PROC/WEB/0] [OUT] Exit status 1
2019-04-08T15:23:14.835+05:30 [CELL/SSHD/0] [OUT] Exit status 0
2019-04-08T15:23:14.918+05:30 [CELL/0] [OUT] Cell 442a8bb7-ca77-4a68-983b-923c300d7558 stopping instance f7147956-5464-4f03-6764-259d
2019-04-08T15:23:14.918+05:30 [CELL/0] [OUT] Cell 442a8bb7-ca77-4a68-983b-923c300d7558 destroying container for instance f7147956-5464-4f03-6764-259d
```

How do I resolve this issue?

**Comment by pink95** [comment]
Solution:

manually deleted the jar file with the issue (/tmp/app/WEB-INF/lib/poi-ooxml-schemas-3.11.jar). and ran a clean command. worked like a charm.
