### ISSUE TITLE
Setup Elastic APM with cloudfoundry fails with "No compatible attachment provider is available"

### ISSUE THREAD

**Issue by honnel** [cloudfoundry/java-buildpack#718]
We are trying to setup [elastic apm](https://www.elastic.co/de/solutions/apm) for our applications.

Unfortunately we get following error during application startup:

```
   2019-04-09T10:18:18.79+0200 [APP/PROC/WEB/0] OUT 2019-04-09 08:18:18.793 [apm-server-healthcheck] INFO co.elastic.apm.agent.report.ApmServerHealthChecker - Elastic APM server is available: {"ok":{"build_date":"2019-03-06T14:11:42Z","build_sha":"daad5449d758e7bf101f6482778a2b15f646a67f","version":"6.6.2"}}
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR Exception in thread "main" java.lang.reflect.InvocationTargetException
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR Caused by: java.lang.IllegalStateException: No compatible attachment provider is available
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:416)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:298)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:273)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:260)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:46)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	at ...App.main(App.java:23)
   2019-04-09T10:18:18.80+0200 [APP/PROC/WEB/0] ERR 	... 8 more
```

During staging the apm agent is successfully prepared:

```
   -----> Downloading Elastic Apm Agent 1.5.0 from https://repo1.maven.org/maven2/co/elastic/apm/elastic-apm-agent/1.5.0/elastic-apm-agent-1.5.0.jar (found in cache)
```

We configured manifest with:

```
      JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.+ }, memory_calculator: { stack_threads: 25 } }'
      ...
      ELASTIC_APM_SERVICE_NAME: ((elastic-apm-service-name))
      ELASTIC_APM_APPLICATION_PACKAGES: ((elastic-apm-app-packages))
      ELASTIC_APM_SERVER_URLS: ((elastic-apm-server-urls))
      ELASTIC_APM_SECRET_TOKEN: ((elastic-apm-secret-token))
```

Additionally we defined a user provided service and bound it to our application with:

```bash
cf cups elastic-apm-service -p '{"server_urls":"https://$apm-server:8200","secret_token":"$secret-token"}'
cf bind-service $app elastic-apm-service
```

Is there any misconfiguration?

Pivotal Cloud Foundry API-Version:    2.125.0

**Comment by honnel** [comment]
We found our misconfiguration in our application

We had to change our dependencies defined in `pom.xml`:

```xml
<dependency>
    <groupId>co.elastic.apm</groupId>
    <artifactId>apm-agent-attach</artifactId>
    <version>${elastic-apm.version}</version>
</dependency>
<dependency>
    <groupId>co.elastic.apm</groupId>
    <artifactId>apm-agent-api</artifactId>
    <version>${elastic-apm.version}</version>
</dependency>
````

to:

```xml
<dependency>
    <groupId>co.elastic.apm</groupId>
    <artifactId>apm-agent-api</artifactId>
    <version>${elastic-apm.version}</version>
</dependency>
````

Because the JavaBuild Pack does not use the "Programmatic API setup to self-attach - Use the apm-agent-attach artifact and the attachAPI to set up the agent."-Setup as decribed here: https://www.elastic.co/guide/en/apm/agent/java/current/setup.html 

Its just the javaagent which is described as "Manual setup with --javaagent flag - Manually set up and configure the agent with the --javaagent JVM flag."

Afterwards the buildpack works as expected for us.👍
