### ISSUE TITLE
Java buildpack questions about offline package creation issues

### ISSUE THREAD

**Issue by grapematstar** [cloudfoundry/java-buildpack#816]
Hi
Our currently operating CF runs on openstack, a private iaas.
This CF has default buildpack installed, but due to private firewall, java buildpack must be used via offline package.

Following the described guide, I created a public linux VM on AWS, and when I try to create an offline package in this environment, the following message is output and the creation of the offline package stops.
```
...
Pinning azure_application_insights_agent version to 2.6.1
Pinning client_certificate_mapper version to 1.11.0_RELEASE
Pinning container_customizer version to 2.6.0_RELEASE
Pinning container_security_provider version to 1.18.0_RELEASE
Pinning contrast_security_agent version to 3.7.5_15818
Pinning dynatrace_appmon_agent version to 7.1.0_1803
Pinning elastic_apm_agent version to 1.17.0
Pinning google_stackdriver_debugger version to 2.25.0
Pinning google_stackdriver_profiler version to 0.1.0
Pinning introscope_agent version to 20.6.0_28
Pinning jacoco_agent version to 0.8.5
Pinning agent version to 0.5.0
Pinning clean_up version to 0.1.0
Pinning jprofiler_profiler version to 11.1.3
Pinning jrebel_agent version to 2020.2.3
[DownloadCache]                  WARN  Unable to download https://files.cf-hsm.io/luna-installer/index.yml into cache build/staging/resources/cache: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
rake aborted!
Unable to find cached file for https://files.cf-hsm.io/luna-installer/index.yml
/home/ubuntu/downloads/buildpack/java-buildpack-4.32/lib/java_buildpack/util/cache/download_cache.rb:79:in `get'
/home/ubuntu/downloads/buildpack/java-buildpack-4.32/rakelib/dependency_cache_task.rb:183:in `get_from_cache'
/home/ubuntu/downloads/buildpack/java-buildpack-4.32/rakelib/dependency_cache_task.rb:175:in `block (2 levels) in uris'
/home/ubuntu/downloads/buildpack/java-buildpack-4.32/rakelib/dependency_cache_task.rb:173:in `each'
/home/ubuntu/downloads/buildpack/java-buildpack-4.32/rakelib/dependency_cache_task.rb:173:in `block in uris'
/home/ubuntu/downloads/buildpack/java-buildpack-4.32/rakelib/dependency_cache_task.rb:172:in `each'
/home/ubuntu/downloads/buildpack/java-buildpack-4.32/rakelib/dependency_cache_task.rb:172:in `uris'
/home/ubuntu/downloads/buildpack/java-buildpack-4.32/rakelib/dependency_cache_task.rb:46:in `initialize'
/home/ubuntu/downloads/buildpack/java-buildpack-4.32/Rakefile:42:in `new'
/home/ubuntu/downloads/buildpack/java-buildpack-4.32/Rakefile:42:in `<top (required)>'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

 java buildpack version I used to create offline packages is v4.32.

I am wondering what part to check to solve this problem.
thanks.

**Comment by nebhale** [comment]
This appeared to be a problem with one of our partner integrations having an expired certificate.  This certificate has now been renewed.
