### ISSUE TITLE
Extending the classpath via multiple buildpack

### ISSUE THREAD

**Issue by raman-nbg** [cloudfoundry/java-buildpack#818]
I have a Spring Boot app that uses the java buildpack and [another buildpack](https://github.com/datev/mapr-buildpack/settings). The Spring Boot app is launched with the Main Class Container of the java buildpack.

To use the other buildpack correctly we have to extend the classpath of the app. Is it somehow possible to extend the classpath via multiple buildpack?

I tried to provide `additional_libraries`. But it seems that this only tries to copy single files. I can not add a directory. Also the listed files need to be a zip (?). In my case I want to add a directory containing xml-files to the classpath.

First I got the following exception when I try to add a path to `addiotional_libraries`:
```
2020-07-30T16:38:20.322+02:00 [APP/PROC/WEB/0] [ERR] Exception in thread "main" java.lang.IllegalArgumentException: File /home/vcap/app/BOOT-INF/lib/core-site.xml must exist
2020-07-30T16:38:20.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.openIfNecessary(RandomAccessDataFile.java:233)
2020-07-30T16:38:20.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.<init>(RandomAccessDataFile.java:215)
2020-07-30T16:38:20.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.data.RandomAccessDataFile$FileAccess.<init>(RandomAccessDataFile.java:205)
2020-07-30T16:38:20.323+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.data.RandomAccessDataFile.<init>(RandomAccessDataFile.java:50)
2020-07-30T16:38:20.323+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:91)
2020-07-30T16:38:20.323+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61)
2020-07-30T16:38:20.323+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57)
2020-07-30T16:38:20.323+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchive(ExplodedArchive.java:119)
2020-07-30T16:38:20.323+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchives(ExplodedArchive.java:106)
2020-07-30T16:38:20.323+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:69)
2020-07-30T16:38:20.323+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2020-07-30T16:38:20.323+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
```

In the second case I tried to add only a single xml-file to `additional_libraries`. Then I got the following error:
```
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] Exception in thread "main" java.util.zip.ZipException: error in opening zip file
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at java.util.zip.ZipFile.open(Native Method)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at java.util.zip.ZipFile.<init>(ZipFile.java:225)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at java.util.zip.ZipFile.<init>(ZipFile.java:155)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at java.util.jar.JarFile.<init>(JarFile.java:166)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at java.util.jar.JarFile.<init>(JarFile.java:130)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:119)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:114)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:100)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:91)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:61)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.JarFileArchive.<init>(JarFileArchive.java:57)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchive(ExplodedArchive.java:119)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.archive.ExplodedArchive.getNestedArchives(ExplodedArchive.java:106)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:69)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
2020-07-30T16:54:53.322+02:00 [APP/PROC/WEB/0] [ERR] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
```

**Comment by nebhale** [comment]
You're in the right area [based on the documentation](https://github.com/cloudfoundry/java-buildpack/blob/main/docs/framework-multi_buildpack.md#multiple-buildpack-integration-api).  If you have a directory of JAR files that all need to be on the classpath, your "other" buildpack should iterate over the collection and add each as a line-item to the `additional_entries` section.

But, based on the error messages that you're seeing, it appears that you're trying to do something other than adding some additional libraries.  Can you please elaborate on what you're doing?

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
